### ISSUE TITLE
Barcode scanner's canvas is not painting at the correct position

### ISSUE THREAD

**Issue by prooshani** [flutter-ml/google_ml_kit_flutter#248]
I am using this awesome plug-in and appreciate for the effort you are sharing.
I am using barcode scanner and I have problem with the position of rectangle (canvas) which is painting around the detected barcode.
I have spent a good time finding the source of problem but I was not able to find it.

Has anyone faced the same problem?
or
Has anyone know how I can fine tune the location of the painted canvas?

**Comment by fbernaly** [comment]
@prooshani : have you try out example app? We are drawing a rect on top using he corners. Is that what you want to achieve?

**Comment by prooshani** [comment]
Yes, I have tried that and it is far top from the detected barcode and make it complicated especially when there is multiple  barcodes available.
In fact, if we have 2-3 barcodes on top of each other, you cannot decide which painted rect belongs to which barcode.

**Comment by fbernaly** [comment]
Could you share a screenshot of what you are getting? And what device are you using for testing?

**Comment by 049er** [comment]
Hi, I'm having a similar problem with the example app. (Xiaomi Redmi Note 10s)
The barcodes are not being outlined properly.

![Screenshot_2022-05-31-13-10-00-981_com google_mlkit_example](https://user-images.githubusercontent.com/22274130/171160546-23c067a4-849d-4785-b145-2579a4f1e5d5.jpg)

Flutter Doctor:
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 22.04 LTS 5.15.0-33-generic, locale en_ZA.UTF-8)
    • Flutter version 3.0.1 at /home/werner/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (12 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/werner/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /snap/android-studio/119/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.1)
    • Android Studio at /snap/android-studio/119/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • M2101K7BG (mobile) • AMBIJFLB9T757DOR • android-arm64  • Android 11 (API 30)
    • Linux (desktop)    • linux            • linux-x64      • Ubuntu 22.04 LTS 5.15.0-33-generic
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by fbernaly** [comment]
@049er: that is an issue in the example app (outside the actual plugin) that it is not resizing correctly the output of the detection (the plugin). Feel free to send a PR fixing the barcode painter: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/painters/barcode_detector_painter.dart We always welcome contributions.
