### ISSUE TITLE
weird issue for Text Detector in landscape orientation

### ISSUE THREAD

**Issue by prooshani** [flutter-ml/google_ml_kit_flutter#253]
I am working with ML Kit Text Detector recently and found that there is a problem in detecting texts in landscape mode.
While it is working OK in portrait mode, in landscape mode it is not working correctly for horizontal texts but verticals.
I mean, if you put a text in the same orientation of the camera (as a normal way to do so) it will not detect any text but, if you rotate the text by 90 degrees it will detect the text easily BUT the painter will draw the canvas and show the recognizedText in the correct orientation!!

I got some pics to show you guys what I mean.

As you can see, it is a vivid number which the ML kit text detector can easily detect it if the camera orientation was portrait but, in landscape mode, it cannot detect it when it is in the same orientation of the camera (90 degrees)
![IMG_8991](https://user-images.githubusercontent.com/69037930/168380821-d9d7c046-2134-49ba-ac3d-b1052d526c34.jpg)

Now, if we rotate the text in front of a landscape camera (rotate by 90 degrees) it will detect the text very fast and easy while the preview of the recognizedText is in the correct orientation of the device! : 

![IMG_8992](https://user-images.githubusercontent.com/69037930/168381254-cb7a4c88-0c0d-4f8b-b2cb-223314949132.jpg)

I had tried so many things in CameraView, processImage and all but with zero effort!
Anyone have any idea what should I can do to solve this issue?

**Comment by fbernaly** [comment]
@prooshani: I think it is related to the same ImageRotation issue https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/240, you need to figure out the rotation for the `InputImage`. As long a you pass the correct `InputImage` with the correct orientation and metadata, the plugin will detect the text correctly. It is not the plugin not working, but the InputImage with wrong orientation.

The example app has some known issues, and the painter needs some tweaking to have it working correctly in both portrait and landscape. So far I think the plugin is working fine, but the painter is outside the scope of this plugin, I added it in the example app only for demo purposes, and it is not production code. Feel free to improve the example app and send your PR.

Let's keep open this issue if you decide to send a PR and improve the example app, otherwise let's close it.

**Comment by prooshani** [comment]
> @prooshani: I think it is related to the same ImageRotation issue #240, you need to figure out the rotation for the `InputImage`. As long a you pass the correct `InputImage` with the correct orientation and metadata, the plugin will detect the text correctly. It is not the plugin not working, but the InputImage with wrong orientation.
> 
> The example app has some known issues, and the painter needs some tweaking to have it working correctly in both portrait and landscape. So far I think the plugin is working fine, but the painter is outside the scope of this plugin, I added it in the example app only for demo purposes, and it is not production code. Feel free to improve the example app and send your PR.
> 
> Let's keep open this issue if you decide to send a PR and improve the example app, otherwise let's close it.

I have fixed the barcode and zoomed camera preview in barcode scanner and camera_view and I will re-check and PR the results. However, I need more tweaking for the camera view and I think there is something wrong in InputImageData's rotation attribute. I have checked and it is returning 90 degrees at all orientations which is not correct and make these issues for the example app which is kinda a shortcut to implement the plug-in inside the final apps.

**Comment by prooshani** [comment]
I have found the problem root.
This part from camera_view cannot detect and reflect the correct orientation of the screen and camera. Therefore, the detected barcode/text and etc are faulty in landscape mode:

```
final imageRotation =
        InputImageRotationValue.fromRawValue(camera.sensorOrientation) ??
            InputImageRotation.rotation0deg;
```

**Comment by fbernaly** [comment]
Do you have a fix for that?

**Comment by prooshani** [comment]
> Great!!! Do you have a fix for that? Thanks for debugging

Working on it.
Will let you know here.

**Comment by prooshani** [comment]
> Great!!! Do you have a fix for that? Thanks for debugging

OK, after spending hours to find a flutter SDK's native class to detect exact orientation (PortraitUP, PortraitDown, landscapeLeft, landscaperight) I have found that this will not happen without and external package like [Native Device Orientation](https://pub.dev/packages/native_device_orientation).
I don't know if you have any interest to fix the example code using any external package or not.
If so, please let me know to check the package and implement it into the example code.

**Comment by fbernaly** [comment]
Yea, go ahead and fix the example app using the external package. Update the readme as needed.
