### ISSUE TITLE
Custom object detection model giving wrong predictions on Android

### ISSUE THREAD

**Issue by DeepakSinghRawat** [flutter-ml/google_ml_kit_flutter#275]
Hi,

I am trying to use a custom object detection model in the example app provided by you. I am using the latest version of [google_mlkit_object_detection: ^0.4.0](https://pub.dev/packages/google_mlkit_object_detection) plugin.

I replaced the [object_labeler.tflite](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/assets/ml/object_labeler.tflite) model in the example app with a custom model. I want to get predictions using `camera live feed`.  The model is predicting correct labels on iOS. But for some reason it's not predicting correct labels on Android. I am testing on Android 10. On Android it's predicting random values. If I use a single image from the gallery or take a picture then I am getting good predictions on Android also.

I used the same model in the [ML Kit Vision Quickstart Sample Android App](https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart) and it's giving correct predictions.

My current settings:

``` 
    final options = LocalObjectDetectorOptions(
      mode: mode,
      modelPath: modelPath,
      classifyObjects: true,
      multipleObjects: true,
    );

CameraController(
      camera,
      ResolutionPreset.high,
      enableAudio: false,
    );
```

I have tried to change `ResolutionPreset` to different values but nothing is working. Please guide me on how to resolve this issue.

**Comment by fbernaly** [comment]
@DeepakSinghRawat: could you share your custom model, I will take a look.

**Comment by DeepakSinghRawat** [comment]
@fbernaly Please download the model from [here](https://drive.google.com/file/d/1lTuoCKZFtumeckqmqh8Hde4J__JRBH65/view?usp=sharing). Let me know if you need any other information.

**Comment by fbernaly** [comment]
@DeepakSinghRawat : I created this branch with you model: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/fruits_model

Give it a try. 

I am not an expert in Machine Learning or trying models. I cannot tell you if the model is well trained or not, but so far the testing I did with my Pixel4 I am getting this:

![Screenshot_20220602-151324](https://user-images.githubusercontent.com/7014968/171751258-2cab179e-598e-4c53-b4fb-37f05d21ff74.png)

![Screenshot_20220602-151309](https://user-images.githubusercontent.com/7014968/171751276-39d8ab60-fb4f-4814-8bcd-5cef9ce10235.png)

**Comment by DeepakSinghRawat** [comment]
Dear @fbernaly Thank you for taking a look at the issue I am facing. I tried your repo on a few real fruits but got wrong predictions. For example here are the predictions from your flutter app and mlkit's android app. Flutter app is predicting `apple` which is wrong. mlkit's android app is predicting `tomato` for the same image which is correct. I even changed `multipleObjects: false` in the flutter app but still got wrong predictions most of the time. For the same images, the flutter app on iPhone is working fine. I am facing this issue only on Android. 

I have created a new repo with mlkit's android app and my model in case you want to install it and compare the results. Here's the [link](https://github.com/DeepakSinghRawat/mlkit) 


### Original Image
![original_tomatoes](https://user-images.githubusercontent.com/263447/171881012-20206823-f8b1-401b-9820-cd911c38e39a.jpg)

### Flutter App Prediction
![flutter_app](https://user-images.githubusercontent.com/263447/171881042-aa1c5983-3f4a-4f3c-b1f8-ffda38658c0d.jpg)

### MLKIT Android App Prediction
![android_app](https://user-images.githubusercontent.com/263447/171881066-117a20d9-e26b-4758-ba51-4e41490d0a1a.jpg)

**Comment by Heech** [comment]
I'm having a similar problem when trying to use our custom model in the object detection example project.
Seeing the same results as when the default `assets/object_labeler.tflite` model is used. 
Even when changing to a non-existing file path the app gives no errors but showing same results regardless.

**Comment by minhquangkid** [comment]
@DeepakSinghRawatI I don't know how to trained a custom detection model using a pre-trained model as you did, please show me the way to do it, thank you!
