### ISSUE TITLE
Issue with IOS devices

### ISSUE THREAD

**Issue by GeorgeSamirTechno-politan** [flutter-ml/google_ml_kit_flutter#299]
Facing issue while detecting face images on IOS devices with lower front camera resolutions (iPhone 8).
Although there is no problem with iPhone XS (which has face detection camera).
If we use the same iPhone 8 camera to take a photo then use the algorithm to process it, it works fine. But doesnt work on images taken directly by the camera.
How can we workaround this issue?

**Comment by fbernaly** [comment]
Make sure your input image conforms with these resolution guidelines: https://developers.google.com/ml-kit/vision/face-detection/ios#input-image-guidelines
