### ISSUE TITLE
TextRecognizer flat out fails reading embossed text.

### ISSUE THREAD

**Issue by codyfilatov** [flutter-ml/google_ml_kit_flutter#301]
Embossed text, such as a credit card number completely fails at being read.
Printed number text works fine.

What options are available to improve the accuracy of reading embossed numbers? It's half way there, but my app almost entirely relies on the ability to read this type of font.

**Comment by fbernaly** [comment]
@codyfilatov: could you provide a sample image that is failing? I would like to take a look.

**Comment by codyfilatov** [comment]
I am at 0 risk sharing this image, it's just the VISA and bank INI numbers. Nothing is PII.

Please see this image for example, it has extreme trouble identifying the card number text. Particularly the first "4" in the number. I have attempted a few things that did help slightly. I got VERY SLIGHTLY better results processing this same image as greyscale.

![20220724_222912](https://user-images.githubusercontent.com/87826997/180704920-7e7a879c-3362-493e-b352-998eecca475a.jpg)

**Comment by fbernaly** [comment]
Which plugin are you using in your yaml file?

**Comment by codyfilatov** [comment]
> Which plugin are you using in your yaml file?

google_mlkit_text_recognition: 0.3.0
Using TextRecognizer getting the results with nothing fancy. ImageFile is a max resolution image taken from the flutter camera plugin library. I have absolutely 0 problems with printed card text, only embossed cards cause this issue. I can understand it is more challenging to identify them, but if there are suggestions to improve the accuracy it would help significantly.

TextRecognizer textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);
RecognizedText frontText = await textRecognizer.processImage(InputImage.fromFile(imageFile));

**Comment by fbernaly** [comment]
ok, I will take a look

**Comment by fbernaly** [comment]
ios or android?

**Comment by codyfilatov** [comment]
Both platforms but primary testing on android

**Comment by c-louis** [comment]
Certainly related to : 
https://github.com/googlesamples/mlkit/issues/338

**Comment by fbernaly** [comment]
Thanks @c-louis, definitely it is related, if they reported the same issue in the native sample app and since this plugin is a wrapper for the native APIs using FlutterMethodChannel, then we will experience the same issue. 
@codyfilatov: We are going to keep this issue open, but there is nothing we can do until they fix the native libraries. Keep an eye on https://github.com/googlesamples/mlkit/issues/338.
