### ISSUE TITLE
Pose detection in landscape mode

### ISSUE THREAD

**Issue by reza00farjam** [flutter-ml/google_ml_kit_flutter#302]
Hi
In pose detector example, landscape mode is totally unsupported and even set the device to this mode will make the camera to zoom in by default (large scale).
So, does pose detector support landscape mode? What is it's configurations if it does?

**Comment by Faiizii** [comment]
Can you share some more information. Because I tried it today in both MODEs (Portrait and Horizontal) everything was working find.

**Comment by fbernaly** [comment]
Fixed in PR https://github.com/flutter-ml/google_ml_kit_flutter/pull/470
