### ISSUE TITLE
why barcode scanner just find max 10 objects

### ISSUE THREAD

**Issue by kucukkaa** [flutter-ml/google_ml_kit_flutter#306]
im trying on example for understanding how the features works.

in barcode scanner mode(on example) with image from gallery it just find max 10 barcodes. in image there is 25 barcodes and when i try it on camera mod(open image on computer) it can find all barcodes.
when i cut the image(inculude not founded barcodes in orijinal image) and add white areas for set it same size of the original image it can find the other 10 barcodes.

is this an error or is there a limitation here?

thankyou!

**Comment by TahaMsv** [comment]
Hello. I have the same problem. Did you find a solution?

**Comment by fbernaly** [comment]
It has to do with the resolution for each barcode in each image: https://developers.google.com/ml-kit/vision/barcode-scanning/android#input-image-guidelines

Also use NV21 for Android.
In this comment: https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057
Someone reported that the native apps are using that for MLKit and when doing the same in Flutter solved the issue for Android. That was merged in this PR https://github.com/flutter-ml/google_ml_kit_flutter/pull/454. Update to the latest plugin version.
