### ISSUE TITLE
Barecode scanner only scans urls on Nokia X20 

### ISSUE THREAD

**Issue by MenaRaafat** [flutter-ml/google_ml_kit_flutter#309]
The barcode scanner doesn't scan any type of data other than URLs.

This issue is only present on Nokia X20 device
https://www.gsmarena.com/nokia_x20-10838.php

ex:
123 --> No response
ABC  -> No response
https://www.github.com  --> Responds

**Comment by mahmoudsfares** [comment]
Same problem on Oppo A95

**Comment by MuhamadEzzat** [comment]
I faced this issue while using Nokia X20  & Oppo A95

Just accept URLs only!
