### ISSUE TITLE
PlatformException when trying to detect objects on a custom model (3D tensor vs 4D tensor)

### ISSUE THREAD

**Issue by Theunodb** [flutter-ml/google_ml_kit_flutter#313]
I used Cloud AutoML to train a custom model that suppose to detect marks on a piece of paper. I have the dataset exported as a TFLite file, and i have it hosted on firebase.

I managed to download the file and initiate the objectDetector fine. but are getting an error when processing an input image.

This is how i download the model file
```dart
  static Future<File> loadModelFileFromFirebase() async {
    try {
      FirebaseModelDownloader downloader = FirebaseModelDownloader.instance;

      List<FirebaseCustomModel> models = await downloader.listDownloadedModels();
      for (FirebaseCustomModel model in models) {
        print('Name: ${model.name}');
      }

      FirebaseModelDownloadConditions conditions = FirebaseModelDownloadConditions(
        iosAllowsCellularAccess: true,
        iosAllowsBackgroundDownloading: false,
        androidChargingRequired: false,
        androidWifiRequired: false,
        androidDeviceIdleRequired: false,
      );

      FirebaseCustomModel model = await downloader.getModel(
        'xxx',
        FirebaseModelDownloadType.latestModel,
        conditions,
      );

      File modelFile = model.file;

      return modelFile;
    } catch (exception) {
      print('Failed on loading your model from Firebase: $exception');
      print('The program will not be resumed');
      rethrow;
    }
  }
```

This is how i initialise the object detector:
```dart
  static Future<ObjectDetector> initializeLocalDetector(File modelFile, double confidenceThreshold, int maximumLabelsPerObject) async {
    try {
      final options = LocalObjectDetectorOptions(
        mode: DetectionMode.single,
        modelPath: modelFile.path,
        classifyObjects: true,
        multipleObjects: true,
        confidenceThreshold: confidenceThreshold,
        maximumLabelsPerObject: maximumLabelsPerObject,
      );

      return ObjectDetector(options: options);
    } catch (exception) {
      print('Failed on loading your model to the TFLite interpreter: $exception');
      print('The program will not be resumed');
      rethrow;
    }
  }
```

When i call:
```dart
        List<DetectedObject> objects = await state.mainShoddyState.objectDetector!.processImage(inputImage);
```

I get the following error:
```
PlatformException(Error 3, com.google.visionkit.pipeline.error, Pipeline failed to fully start:
CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1)., null)
```

Is there something i'm missing?

**Comment by jasonJamEther** [comment]
I am getting the same error when running my custom model. Mine is stored locally.

**Comment by javiCuara** [comment]
I am getting the same issue with a custom model trained using AutoMl.

**Comment by Theunodb** [comment]
I've explored multiple avenues without any success. It seems like the only way to get models trained with autoML / Vertex ai is to use https://www.tensorflow.org. I've managed to test my models manually with the native example projects they provide.

I guess if we cant get this to work we'll need to create a new plugin

**Comment by javiCuara** [comment]
Thanks for the insight @Theunodb you save me some time! I was about to train a new model using Vertex Ai.

It seems that most of the tflite packages are outdated as well.

**Comment by chapmacl** [comment]
For anyone still wondering, the documentation for this is pretty confusing but you can use custom models for object detection, but only image classification models. You can also see that this is the case when looking at the ML Kit models in tfhub, because their architectures and datasets are image classifiers and image classification problems. The ML Kit object detector uses Google's object detection and tracking API with an image classifier (instead of just using an object detection model). At the moment, we're at the mercy of their object detection API, and it looks like there is still no way to use a custom object detector model.
