### ISSUE TITLE
Face detect not work when using tablet with landscape

### ISSUE THREAD

**Issue by rraayy** [flutter-ml/google_ml_kit_flutter#317]
Hi, I run the face detect sample code on my Samsung S5e tablet and Lenovo M10,
I have a problem when using tablet with landscape mode. 
You can see the preview will zoom in the camera and the face detect won't success.

![222](https://user-images.githubusercontent.com/4694572/185283244-1fb6ac61-5e07-4f86-8e6f-10d22f4cff8d.png)

When run the sample code run in the same tablet with portrait, the face detect will work well.

![333](https://user-images.githubusercontent.com/4694572/185283255-6b9fdb5e-a47c-40c5-9dcd-76e80626bdb7.png)

Are there any way to run the sample code for the android tablet with landscape can work face detection?

<details>
 <summary>flutter doctor -v</summary>
➜  google_ml_kit flutter doctor -v

[✓] Flutter (Channel stable, 3.0.4, on macOS 12.5 21G72 darwin-arm (Rosetta), locale zh-Hant-TW)
    • Flutter version 3.0.4 at /Users/rraayy/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (7 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/rraayy/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • SM T720 (mobile)  • R52M40XX1PZ               • android-arm64  • Android 10 (API 29)
    • iPad Ray (mobile) • 00008020-001148513A69002E • ios            • iOS 14.8.1 18H107
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 12.5 21G72 darwin-arm (Rosetta)
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 104.0.5112.101
    ! Error: 你要吃餅乾嗎🍪？(ᵒ̴̷͈ᗨᵒ  )✧ is not connected. Xcode will continue when 你要吃餅乾嗎🍪？(ᵒ̴̷͈ᗨᵒ  )✧ is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

**Comment by acoutts** [comment]
Are you providing the right rotation to MLKit?

**Comment by acoutts** [comment]
Possibly related to this: https://github.com/flutter/flutter/issues/118350

**Comment by fbernaly** [comment]
Use NV21 for Android.
In this comment: https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057
Someone reported that the native apps are using that for MLKit and when doing the same in Flutter solved the issue for Android. That was merged in this PR https://github.com/flutter-ml/google_ml_kit_flutter/pull/454. Update to the latest plugin version.
