### ISSUE TITLE
Setting enableRawSizeMask: false, crashes the app

### ISSUE THREAD

**Issue by nohe427** [flutter-ml/google_ml_kit_flutter#325]
Using Flutter and deploying to Android. When trying to use selfieSegmentation and grabbing the full mask with `enableRawSizeMask: false,`, my app crashes when running `final mask = await segmenter.processImage(inputImage);`.

**Comment by fbernaly** [comment]
Fixed in this PR: https://github.com/flutter-ml/google_ml_kit_flutter/pull/473
