### ISSUE TITLE
APK size increases by 300MB+ when importing a library (flutter).

### ISSUE THREAD

**Issue by Anpoda** [flutter-ml/google_ml_kit_flutter#326]
Good afternoon! I am writing an application on Flutter and decided to use your library: https://pub.dev/packages/google_ml_kit. 

Before importing the library, the application size was 149MB. After importing and building the APK, the size increased to 420MB. 

Question: if the download limit for Google Play is 150MB for APK, then how can I use the plugin? Can it be compressed?

**Comment by fbernaly** [comment]
Did you read our readme? There we explain that google_ml_kit is the umbrella plugin and there are also individual plugins for each API you can use: like face detection or text detection, etc. Depending of your app you should used one of those individual plugins and that will reduce the size of unnecessary APIs and models, unless your app uses all the APIs then you will need to use the umbrella plugin. Please check out our documentation.
