### ISSUE TITLE
Face Detection doesn't work when face inside identity card, must be zoom

### ISSUE THREAD

**Issue by tegaranugroho** [flutter-ml/google_ml_kit_flutter#340]
I'm trying to detect faces on the ID card, but why when the card frame looks full the face is not detected? only detected when zooming.

Device : Android 12
Lib version :  google_mlkit_face_detection: ^0.4.0

![ezgif-3-318e07434c](https://user-images.githubusercontent.com/21018017/189577050-49d77cdf-ec77-4ddf-9325-0f3e955024ca.gif)

**Comment by vishisht08** [comment]
@tegarnugroho hii i would like to contribute to this issue. please assign me this.

**Comment by tegarnugroho** [comment]
@vishisht08 actually i don't know how to assign task to you in this issue, because I don't have permission to do that, maybe repository owner can give it @bharat-biradar

**Comment by fbernaly** [comment]
From the [documentation](https://developers.google.com/ml-kit/vision/face-detection/android#input-image-guidelines):

> For face recognition, you should use an image with dimensions of at least 480x360 pixels. For ML Kit to accurately detect faces, input images must contain faces that are represented by sufficient pixel data. In general, each face you want to detect in an image should be at least 100x100 pixels. If you want to detect the contours of faces, ML Kit requires higher resolution input: each face should be at least 200x200 pixels.
