### ISSUE TITLE
ML-Kit Face mesh detection - is it a likely future addition?

### ISSUE THREAD

**Issue by lenlaw** [flutter-ml/google_ml_kit_flutter#343]
ML-Kit Face mesh detection -  is it a likely future addition?

**Comment by bensonarafat** [comment]
Hmm, let me see what I can do on this.

**Comment by fbernaly** [comment]
Face Mesh detection is still in Beta and only supported in Android:  https://developers.google.com/ml-kit/vision/face-mesh-detection

In this PR I am adding the plugin with the beta functionality: https://github.com/flutter-ml/google_ml_kit_flutter/pull/476

**Comment by fbernaly** [comment]
Initial version: https://pub.dev/packages/google_mlkit_face_mesh_detection
