### ISSUE TITLE
Pose detection always return one pose

### ISSUE THREAD

**Issue by MaxmaxB** [flutter-ml/google_ml_kit_flutter#344]
Hello I'm using the flutter pose detection kit and it works well for a single person on the image. But if they are more than 1 person on the image it still return only 1 pose. The processImage method return an array of poses so I was expecting that it was supported. Any reason for that? Thanks

**Comment by Maxhoppr** [comment]
This could be reproduce using the example app.

**Comment by Ashkan-Sarlak** [comment]
From [google's documentation](https://developers.google.com/ml-kit/vision/pose-detection):
> Pose detection can only detect one person in an image. If two people are in the image, the model will assign landmarks to the person detected with the highest confidence.
