### ISSUE TITLE
[Barcode_Scanner] ITF bad data

### ISSUE THREAD

**Issue by noga-dev** [flutter-ml/google_ml_kit_flutter#349]
ITF of 26 numbers yields wrong data.

For example this:
![image](https://user-images.githubusercontent.com/2067558/193430060-cdd421df-66ef-45fd-b694-a25fdfb91dce.png)

Yields random data of random length like this:
3330343537383233303435373832333034353738

Or this:
1216171160010131

Or this:
1213141516171812131415161718121314151617

Sometimes it can reproduce the same wrong data, so it's not like it's completely random, but incorrect either way.

**Comment by fbernaly** [comment]
@noga-dev : send a PR with your fix

**Comment by noga-dev** [comment]
> @noga-dev : send a PR with your fix

There's no simple fix. Issue is 2-fold:
First is ml model requiring more training.
Second is instability of ITF format.

The first can be addressed, but not the second.

**Comment by Nitish-Kamath** [comment]
Hey man !! Can you assign me this task :)
