### ISSUE TITLE
App crashes (on iOS) when try to detect face 

### ISSUE THREAD

**Issue by TalebRafiepour** [flutter-ml/google_ml_kit_flutter#365]
error log: 
```
2022-11-11 19:06:21.489 Runner[16926/0x103738580] [lvl=3] +[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
2022-11-11 19:06:21.510 Runner[16926/0x103738580] [lvl=3] +[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.
* thread #3, queue = 'ProviderImageSurfaceCacheQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x1350dc000)
    frame #0: 0x00000001db9238e4 libsystem_platform.dylib`_platform_memmove + 196
libsystem_platform.dylib`_platform_memmove:
->  0x1db9238e4 <+196>: ldnp   x10, x11, [x1, #0x10]
    0x1db9238e8 <+200>: add    x1, x1, #0x20
    0x1db9238ec <+204>: sub    x2, x2, x5
    0x1db9238f0 <+208>: stp    x12, x13, [x0]
Target 0: (Runner) stopped.
Lost connection to device.
```

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.2 21D49 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
``` 

google ml kit version :
```
google_mlkit_face_detection: ^0.5.0
```

**Comment by shaz-tech** [comment]
Facing same issue. @TalebRafiepour Any workaround?

**Comment by TalebRafiepour** [comment]
> Facing same issue. @TalebRafiepour Any workaround?

Not yet :((

**Comment by shaz-tech** [comment]
Hey @TalebRafiepour, This issue is related to a limitation. 

As per the documentation, ML Kit (iOS SDK) does not support 32-bit architectures (i386 and armv7) and  64-bit architectures (x86_64 and arm64).
Reference: https://developers.google.com/ml-kit/migration/ios

@TalebRafiepour  Please go though the doc
Thanks.

**Comment by TalebRafiepour** [comment]
> Hey @TalebRafiepour, This issue is related to a limitation.
> 
> As per the documentation, ML Kit (iOS SDK) does not support 32-bit architectures (i386 and armv7) and 64-bit architectures (x86_64 and arm64). Reference: https://developers.google.com/ml-kit/migration/ios
> 
> @TalebRafiepour Please go though the doc Thanks.

Thanks for you help

**Comment by rvanderlinden** [comment]
> As per the documentation, ML Kit (iOS SDK) does not support 32-bit architectures (i386 and armv7) and 64-bit architectures (x86_64 and arm64). Reference: https://developers.google.com/ml-kit/migration/ios


Perhaps this was just a typo, but note that the linked documentation notes that it **does** support 64-bit architectures: _"ML Kit does support 64-bit architectures (x86_64 and arm64)."_.

**Comment by fbernaly** [comment]
ML Kit does not support 32-bit architectures (i386 and armv7). ML Kit does support 64-bit architectures (x86_64 and arm64).

Refer to our updated [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master#ios).

**Comment by Nasserelbaba** [comment]
i am having the same issue i folowed the docs and still having the same error if you fixed it pls tel me how
