### ISSUE TITLE
Likelihood in Pose landmarks is not reliable

### ISSUE THREAD

**Issue by georgiansarghi** [flutter-ml/google_ml_kit_flutter#366]
**Description**
The pose landmarks returned by `google_mlkit_pose_detection` are very unreliable. For example, in [this video](https://user-images.githubusercontent.com/19435539/201732501-59ad11aa-d39c-4ee8-848e-e64095e5cbff.mov) every landmark drawn as a green circle has `likelyhood >= 0.98`.

I don’t know if this is a problem with the flutter package. If it isn’t, do you know a practical/fast solution to discard poses that are not human?

**Comment by xyzacademic** [comment]
I have the same problem with this plugin. It looks like the mobile version's results are jittering a lot, but the desktop version is much more stable and has a visibility threshold to ignore the low confidence points to be shown. If anybody has a suggestion, I appreciate it very much.

**Comment by mManishTrivedi** [comment]
Strange, There is no desktop or web version of Google Ml Kit. I believe @xyzacademic is using mediapipe. 

+ @georgiansarghi, for maintaining consistent results, the Google Ml kit provides dummy key points but has no idea bout why it's giving likelihood value more than 0.98.  I am also searching for how I can control this. May need some hacks in Google Ml kit or Request to google dev team for some options.

**Comment by fbernaly** [comment]
I believe this is an issue in the model used by the native API, but please refer to the first section of our [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_digital_ink_recognition) to learn how this plugin was built using FlutterChannelMethods to access Google's native APIs and then post the issue in Google's repos.
