### ISSUE TITLE
FaceDetector finds only one face (depending on FaceDetectorOptions)

### ISSUE THREAD

**Issue by yoniker** [flutter-ml/google_ml_kit_flutter#371]
Take this simple snippet of code:

```
var selectedFile = File(result.file.path);
    var inputImage = InputImage.fromFile(selectedFile);
    final options = FaceDetectorOptions(enableContours: true,enableLandmarks: false,enableClassification: false,enableTracking: false);
    final faceDetector = FaceDetector(options: options);
    faces = await faceDetector.processImage(inputImage);
```

-When enableContours is true but everything else is false (that's the default) then it returns only one face (in an image with 8 faces). 

-When both enableContours and enableLandmarks are true, then it finds 7/8 faces for the same image as above (in fast mode which is reasonable) but returns contours for just one face (every other contour eg for any other face is null for all entries).

Test on Latest version ( google_mlkit_face_detection: ^0.5.0),
on several emulators (Nexus 5 API 29 was one of them).

**Comment by fbernaly** [comment]
That is by design:
![Screenshot 2023-06-26 at 10 18 44 AM](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/7788f3d2-00a7-4bde-b7b8-9a85097d70d3)
https://developers.google.com/ml-kit/vision/face-detection/android#1.-configure-the-face-detector
