### ISSUE TITLE
Face Detection Not working on vivo and pocco m3

### ISSUE THREAD

**Issue by irfansadiqdevops** [flutter-ml/google_ml_kit_flutter#373]
Library is returning null values on these two devices. Don't know why. Can anyone help!

**Comment by acoutts** [comment]
https://github.com/flutter/flutter/issues/118350

**Comment by fbernaly** [comment]
Use NV21 for Android.
In this comment: https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057
Someone reported that the native apps are using that for MLKit and when doing the same in Flutter solved the issue for Android. That was merged in this PR https://github.com/flutter-ml/google_ml_kit_flutter/pull/454. Update to the latest plugin version.
