### ISSUE TITLE
face detection

### ISSUE THREAD

**Issue by hoangde2811** [flutter-ml/google_ml_kit_flutter#375]
Dear developer!!!
I have used google_mlkit_face_detection: ^0.5.0 and Nokia android 11 phone to run but it seems google mlkit face detection can't handle my face. On the other hand, I use a samsung a30 and can handle it. Source test is attached at the bottom. Hope the developer can answer and give feedback. Sincerely thank you.
https://github.com/MCarlomagno/FaceRecognitionAuth

**Comment by acoutts** [comment]
You might be having the issue I found here: https://github.com/flutter/flutter/issues/118350

**Comment by fbernaly** [comment]
Use NV21 for Android.
In this comment: https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057
Someone reported that the native apps are using that for MLKit and when doing the same in Flutter solved the issue for Android. That was merged in this PR https://github.com/flutter-ml/google_ml_kit_flutter/pull/454. Update to the latest plugin version.
