### ISSUE TITLE
Mediapipe pose unstable on phone compared to desktop

### ISSUE THREAD

**Issue by usmanroshan** [flutter-ml/google_ml_kit_flutter#387]
Hi, I find the mediapipe pose to be much more unstable on the phone compared to on the desktop. For example on the phone the leg and feet keypoints move a lot whereas on the desktop they are much more stable (for the same video). Are the mediapipe models for phone and desktop different? Is there a way I can stabilize mediapipe pose on the phone? Thanks.

**Comment by fbernaly** [comment]
Google's ML Kit is built only for Mobile. I dont know what API you are using to detect pose in desktop, so therefore I guess they are different models.
Please check out the first section of our [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_pose_detection) to learn how this plugin works and follow from there.
