### ISSUE TITLE
Selfie segmentation leads to crash flutter app 

### ISSUE THREAD

**Issue by IraDolynska** [flutter-ml/google_ml_kit_flutter#393]
I am using https://pub.dev/packages/google_mlkit_selfie_segmentation plugin in Flutter app in this way:

```
 final SelfieSegmenter segmenter =
      SelfieSegmenter(mode: SegmenterMode.single, enableRawSizeMask: false);
 InputImage inputImage = InputImage.fromFile(file);
 SegmentationMask? mask = await segmenter.processImage(inputImage);
```
The app crashed after **segmenter.processImage(inputImage)** line with error: 

```
I0000 00:00:1673613739.739530       2 gl_context.cc:352] GL version: 3.0 (OpenGL ES 3.0 Metal - 99)
I0000 00:00:1673613739.741681       2 gl_context.cc:352] GL version: 3.0 (OpenGL ES 3.0 Metal - 99)
I0000 00:00:1673613739.742395       2 gl_context.cc:352] GL version: 3.0 (OpenGL ES 3.0 Metal - 99)
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x000000021b4c2928 libsystem_platform.dylib`_platform_memmove + 88
libsystem_platform.dylib`:
->  0x21b4c2928 <+88>:  stnp   q0, q1, [x3]
    0x21b4c292c <+92>:  add    x3, x3, #0x20
    0x21b4c2930 <+96>:  ldnp   q0, q1, [x1]
    0x21b4c2934 <+100>: add    x1, x1, #0x20
Target 0: (Runner) stopped.
Lost connection to device.
```
This start to reproduce very often after flutter upgrade.
Current Flutter version is  3.3.4.

Are there any changes and improvements planned for this package? Because this is really core feature of my project and now it is working very unstable because of this issue.

**Comment by Snehal-Singh174** [comment]
I am facing the same issue, getting the following error:
`java.lang.OutOfMemoryError: Failed to allocate a 55380616 byte allocation with 25165824 free bytes and 30MB until OOM, target footprint 261761336, growth limit 268435456` 
I even tried the stackoverflow solution, but it didn't worked
https://stackoverflow.com/questions/32244851/androidjava-lang-outofmemoryerror-failed-to-allocate-a-23970828-byte-allocatio

**Comment by momasal** [comment]
I am using **google_mlkit_pose_detection** package and have the same issue.
The only solution I found for it is [](https://developers.google.com/ml-kit/known-issues)
But I don't know how to implement it inside Flutter.

**Comment by maciejbrzezinski** [comment]
In my case It was caused with face detection on iOS by Flutter bug, here more info: https://github.com/flutter/flutter/issues/122792

It was repaired, I was testing on master channel and it works fine now

**Comment by fbernaly** [comment]
That will be fixed in this PR: https://github.com/flutter-ml/google_ml_kit_flutter/pull/473
