### ISSUE TITLE
Number detection in 7 segment display

### ISSUE THREAD

**Issue by Saad29** [flutter-ml/google_ml_kit_flutter#399]
The detection of numbers while using text recognition is quite poor on 7 segment displays. Is there any settings that I should take care of or I am missing something? Or does this library cannot actually detect digits in 7 segment displays?

**Comment by damianjasinski** [comment]
Im also facing same problem

**Comment by MLZ91** [comment]
just realized this problem as well

**Comment by fbernaly** [comment]
I dont think 7 segments displays in included in [Google's API](https://developers.google.com/ml-kit/vision/text-recognition/v2).
