### ISSUE TITLE
image rotation

### ISSUE THREAD

**Issue by maneesh8123** [flutter-ml/google_ml_kit_flutter#407]
Can't detect faces when changing device orientation,can only detect potrait mode in real time face detection

this is the link of the code (real time face recognition) : https://github.com/maneesh8123/https---github.com-maneesh8123-Realtime-Face-Recognition

**Comment by mManishTrivedi** [comment]
I am also facing the same issue in Pose-Detection SDK. When I interchange x and y coordinates in landscape mode then it works as expected.
