### ISSUE TITLE
can't run my project using google_mlkit_text_recognition: ^0.5.0

### ISSUE THREAD

**Issue by dimas96maulana** [flutter-ml/google_ml_kit_flutter#412]
i use dependencies google_mlkit_text_recognition: ^0.4.0 my project can run with sdk: ">=2.12.0 <3.0.0" but i try dependencies google_mlkit_text_recognition: ^0.5.0 with sdk: ">=2.12.0 <3.0.0 " My project is not running, with the error `Error: Type 'Rect' not found. final Rect boundingBox;` ../…/src/text_recognizer.dart:77

Is there a setting that I haven't set yet?

**Comment by qcuong97** [comment]
U should try `google_mlkit_face_detection: ^0.4.0`

**Comment by fbernaly** [comment]
Try latest version
