### ISSUE TITLE
Tflite model created not working and not showing labels

### ISSUE THREAD

**Issue by arrrrny** [flutter-ml/google_ml_kit_flutter#413]
I have created tflite models successfully by following these colabs
https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb

and also original by Google

https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb

Both evalutates good on the colab however When I upload it to sample app here, it doesnt work. 2 issues:

1 it displays boxes but also for unnecessary items, laptop instead of salad,
2 it doesnt display labels around boxes. 

What am I missing? Tflite models work on colab just fine.

**Comment by fbernaly** [comment]
You need to add the metadata to the generated model: 
* https://www.tensorflow.org/lite/models/convert/metadata
* https://developers.google.com/ml-kit/custom-models#metadata

You can read more about [Custom models with ML Kit here](https://developers.google.com/ml-kit/custom-models)
