### ISSUE TITLE
angle property needed for TextLine, TextElement

### ISSUE THREAD

**Issue by mzwtjp** [flutter-ml/google_ml_kit_flutter#420]
As you can see below, MLKit recognized text (Line, Element, Symbol) has angle information and it can be obtained using getAngle() call.

https://developers.google.com/android/reference/com/google/mlkit/vision/text/Text.Element

Knowing angle is very important if I were to show preview and render recognized texts overlayed on image, and when image is slightly rotated (that frequently happens.)

**Comment by mzwtjp** [comment]
Text.Line/Element.getAngle() method availability

(android)
com.google.mlkit:text-recognition:16.0.0-beta5 - NG
com.google.mlkit:text-recognition:16.0.0-beta6 - OK

**Comment by EduardoDiNizo** [comment]
Will these features be added to the ml kit library in Flutter?

I need to get OCR confidence in the reads.

**Comment by fbernaly** [comment]
this was included in https://github.com/flutter-ml/google_ml_kit_flutter/pull/451
Try latest version
