### ISSUE TITLE
Rectangle in the center area

### ISSUE THREAD

**Issue by b4ra0** [flutter-ml/google_ml_kit_flutter#422]
I'm using the google_mlkit_text_recognition, and i needed to recognized a text, but only the one in a rectangle area, just like the [material example](https://m2.material.io/design/machine-learning/barcode-scanning.html#components).
I already tried with CustomPainter, but I can't set the area to process the image.
![image](https://user-images.githubusercontent.com/62418090/229502348-1e4745db-c347-41fb-a424-6bcecbfc85db.png)

**Comment by mzwtjp** [comment]
In my case, I just picked only the bboxes within the area, from the array of total bboxes.

**Comment by b4ra0** [comment]
> In my case, I just picked only the bboxes within the area, from the array of total bboxes.
> 

Did u use this method for your project?

**Comment by mzwtjp** [comment]
Kind of.
I needed to make this 'detection area' resizable (by drag gesture), and reconstructing input image often with different sizes just seemed too complex and performance penalty.  So I just give whole camera image always to the recognizer.
