### ISSUE TITLE
Error build on iOS Build 

### ISSUE THREAD

**Issue by ShailersSolutions** [flutter-ml/google_ml_kit_flutter#425]
Showing this error when i creating for iOS

[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.4.0, which depends on
      Firebase/Auth (= 10.7.0) was resolved to 10.7.0, which depends on
        FirebaseAuth (~> 10.7.0) was resolved to 10.7.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_mlkit_image_labeling (from `.symlinks/plugins/google_mlkit_image_labeling/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/ImageLabelingCustom (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitImageLabelingCustom (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

CocoaPods could not find compatible versions for pod "MLKitVision":
  In Podfile:
    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.2.0, which depends on
      MLKitVision

    google_mlkit_image_labeling (from `.symlinks/plugins/google_mlkit_image_labeling/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/ImageLabelingCustom (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitImageLabelingCustom (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2)

CocoaPods could not find compatible versions for pod "MLKitXenoCommon":
  In Podfile:
    google_mlkit_pose_detection (from `.symlinks/plugins/google_mlkit_pose_detection/ios`) was resolved to 0.5.0, which depends on
      GoogleMLKit/PoseDetection (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitPoseDetection (~> 1.0.0-beta10) was resolved to 1.0.0-beta11, which depends on
          MLKitXenoCommon (= 1.0.0-beta11)

    google_mlkit_selfie_segmentation (from `.symlinks/plugins/google_mlkit_selfie_segmentation/ios`) was resolved to 0.2.0, which depends on
      GoogleMLKit/SegmentationSelfie (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitSegmentationSelfie (~> 1.0.0-beta8) was resolved to 1.0.0-beta8, which depends on
          MLKitSegmentationCommon (= 1.0.0-beta8) was resolved to 1.0.0-beta8, which depends on
            MLKitXenoCommon (= 1.0.0-beta10)

**Comment by fbernaly** [comment]
We know that this plugin has some issue when used with other firebase dependencies. But that is outside the scope of our plugin. 
This plugin is not sponsor or maintained by Google. The [authors](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/AUTHORS) are developers excited about machine learning that wanted to expose Google's native APIs to Flutter.
Once Google updates the collisions between their multiple dependencies we will be able to update this plugin.
