### ISSUE TITLE
Flutter App crashes when invoking FaceDetector.processImage(InputImage)

### ISSUE THREAD

**Issue by Ayan-Qolaris** [flutter-ml/google_ml_kit_flutter#434]
My Flutter App is crashing when faceDetector.processImage(inputImage) is being called. I am not getting any error in log, the camera freezes and the app crashes after 2-3 seconds. What is the cause of the issue, and how to resolve it?

I am using **google_mlkit_face_detection: ^0.6.0**

**Comment by fbernaly** [comment]
Try latest version, and run our example app to see how to consume the plugin.
