### ISSUE TITLE
App not responding when using google_mlkit_barcode_scanning: 0.6.0 on Android 13

### ISSUE THREAD

**Issue by rachanapawar** [flutter-ml/google_ml_kit_flutter#439]
I have using latest google ml kit barcode scanning version in flutter app it worked fine for Android 12 but when I build the app in Android 13, I am getting "App not Responding" pop-up. Once I reopen the app, again after certain time I get this pop-up.

plugin : google_mlkit_barcode_scanning: 0.6.0

**Comment by fbernaly** [comment]
We do not have such pop-up, try the latest version of our example app to see how you can consume this plugin.
