### ISSUE TITLE
Why can not detect all the barcodes in the image?

### ISSUE THREAD

**Issue by TahaMsv** [flutter-ml/google_ml_kit_flutter#440]
Hi. I have an image(From the gallery) that includes up to 40 barcodes, but only 2 or 3 can be recognized. Occasionally, after removing the recognized barcodes, the scanner is able to detect another barcode.

How can I read all of them?

This is my code:

      File file = File(path);
      final List<BarcodeFormat> formats = [BarcodeFormat.all];
      final barcodeScanner = BarcodeScanner(formats: formats);
      final InputImage inputImage = InputImage.fromFile(file);
      final List<Barcode> barcodesResult = await barcodeScanner.processImage(inputImage);
      for (Barcode barcode in barcodesResult) {
        final String? displayValue = barcode.displayValue;
        print(displayValue);
      }

Image:

![image](https://user-images.githubusercontent.com/66914340/236818150-48d0e724-1d8e-49d3-a842-80a69ce75ebe.png)

**Comment by fbernaly** [comment]
That is a limitation from the Google's Barcode API, it will return only just a few depending on the quality of your images. Per documentation: This API recognizes no more than 10 barcodes per API call. https://developers.google.com/ml-kit/vision/barcode-scanning

You can also try their native sample app and make sure you get the same result with their app: https://github.com/googlesamples/mlkit
