### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_MLKTextRecognizer

### ISSUE THREAD

**Issue by mibcoder** [flutter-ml/google_ml_kit_flutter#441]
Step#1
Created a flutter module and added this dependency **google_mlkit_text_recognition: ^0.6.0**

Step#2
Created .xcframework using the command **flutter build ios-framework**

Step#3 
Create a simple iOS file add links and embed frameworks there
![iScreen Shoter - Xcode - 230509151636](https://user-images.githubusercontent.com/110291681/237053207-601d969f-2edc-4a6b-a8bf-9057f08f5cf2.jpg)
`
import SwiftUI

import Flutter

// The following library connects plugins with iOS platform code to this app.
import FlutterPluginRegistrant

class FlutterDependencies: ObservableObject {
  let flutterEngine = FlutterEngine(name: "my flutter engine")
    var myChannel: FlutterMethodChannel!

    
  init(){
      // Runs the default Dart entrypoint with a default Flutter route.
      flutterEngine.run()
      // Connects plugins with iOS platform code to this app.
      GeneratedPluginRegistrant.register(with: self.flutterEngine);
  }
    
}

@main
struct OcrAppOneApp: App {
    
    // flutterDependencies will be injected using EnvironmentObject.
     @StateObject var flutterDependencies = FlutterDependencies()
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

`
**Note:** For step 2&3 I follow https://docs.flutter.dev/add-to-app/ios/project-setup

Step#4
Run app on iPhone, getting this error:
![iScreen Shoter - Xcode - 230509151940](https://user-images.githubusercontent.com/110291681/237053351-68916bcf-ed3e-4a71-849f-7250939b1ef0.jpg)

**Comment by fbernaly** [comment]
I am not familiar with the steps you are following. To integrate any of our plugin in iOS, please follow steps in our readme: https://github.com/flutter-ml/google_ml_kit_flutter#ios

**Comment by patelnirav48** [comment]
@mibcoder Do you get any solution for this? Im also getting same error now

**Comment by AleSpero** [comment]
+1 Happening to me as well. @fbernaly Those are the steps to create a flutter module and place it inside a native app project.
