### ISSUE TITLE
When i try to use custom model its give a exception of Failed to initialize detector

### ISSUE THREAD

**Issue by HumzaKhan071** [flutter-ml/google_ml_kit_flutter#442]
Exception has occurred.
PlatformException (PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException: Failed to initialize detector. Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images., null, null))

**Comment by bensonarafat** [comment]
@HumzaKhan071  which of the package are u using ?

**Comment by HumzaKhan071** [comment]
@bensonarafat i am using flutter_tflite 1.0.1 package

**Comment by bensonarafat** [comment]
which of the Google ml kit plugins are u using?

**Comment by HumzaKhan071** [comment]
@bensonarafat i am using ml_objection_detection

**Comment by fbernaly** [comment]
Any update on this one, or closing by inactivity

**Comment by bensonarafat** [comment]
> @bensonarafat i am using ml_objection_detection

alright

**Comment by bensonarafat** [comment]
> PlatformException (PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException: Failed to initialize detector. Input tensor has type kTfLiteFloat32: it requires specifying NormalizationOptions metadata to preprocess input images., null, null))

Hi @HumzaKhan071, 
I think this is outside the scope. 
MLKit sample application requires additional metadata information to proceed with the tasks. Please refer to https://www.tensorflow.org/lite/models/convert/metadata for filling up the necessary metadata for your model.
