### ISSUE TITLE
Data not uploaded on Firestore 

### ISSUE THREAD

**Issue by shahzaib-official** [flutter-ml/google_ml_kit_flutter#447]
When i use google mlkit package. my app data not send to firebase and also not retrieve. Show me this error
W/Firestore(14774): (24.3.1) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=INTERNAL, description=error in frame handler, cause=java.lang.NoSuchMethodError: No interface method getBuffer()Lokio/Buffer; in class Lokio/BufferedSource; or its super classes (declaration of 'okio.BufferedSource' appears in /data/app/~~78HZ8Fk1MJgOE7xdi8LOug==/com.example.practice-1ftF9iiGlE0pERo_iM1WcA==/base.apk!classes7.dex)
W/Firestore(14774): 	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.data(OkHttpClientTransport.java:1123)
W/Firestore(14774): 	at io.grpc.okhttp.internal.framed.Http2$Reader.readData(Http2.java:234)
W/Firestore(14774): 	at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:147)
W/Firestore(14774): 	at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1082)
W/Firestore(14774): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/Firestore(14774): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/Firestore(14774): 	at java.lang.Thread.run(Thread.java:1012)
W/Firestore(14774): }
W/Firestore(14774): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

Plz solve this issue as soon as possible. When i remove this package app is working well

**Comment by fbernaly** [comment]
@shahzaib-official : please read our README to learn how our plugin works. We won't be able to fix any particular issue that is reported because our env or dependencies could be configure in a different way, so, I suggest you clone our repo, point your yaml file to point to the local copy of the clones repo and start debugging. Contributions are always welcome. Also, look at the issues reported on Firebase in our page and README, hopefully another devs has gone through the same as you and that can help you. Thanks.

**Comment by shahzaib-official** [comment]
I will use this for face detection. I will try many but still not solve the issue

**Comment by fbernaly** [comment]
Look at other similar issues reported when using this plugin along with Firebase: [issues](https://github.com/flutter-ml/google_ml_kit_flutter/issues?q=label%3AFirebase+is%3Aclosed)
