### ISSUE TITLE
Flutter - add confidence score to TextBlock/Line/Element

### ISSUE THREAD

**Issue by EduardoDiNizo** [flutter-ml/google_ml_kit_flutter#448]
https://developers.google.com/android/reference/com/google/mlkit/vision/text/Text.Element

Will these features be added to the ml kit - text recognition library in Flutter?

I need to get OCR confidence score in the reads.

```
for (final line in textBlock.lines) {
          print(' line Text: ${line.text}');
          print(' line Rect: ${line.boundingBox.toString()}');
          print(' line CornerPoints: ${line.cornerPoints.toString()}');
          print(' line confidence: ${line.confidence.toString()}');
          print(' line confidence: ${line.angle.toString()}');
}
```

```
for (final element in line.elements) {
          print(' element Text: ${element.text}');
          print(' element Rect: ${element.boundingBox.toString()}');
          print(' element CornerPoints: ${element.cornerPoints.toString()}');
          print(' element confidence: ${element.confidence.toString()}');
}
```

 java example - https://github.com/googlesamples/mlkit/blob/master/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/java/textdetector/TextGraphic.java

**Comment by fbernaly** [comment]
@EduardoDiNizo : I do not have an ETA for that, but go to our README, understand how this plugins works, learn about Flutter MethodChannels and feel free to send a PR with your contribution. Contributions are always welcome. I will review, merge your PR, and release a new version ASAP.

**Comment by bensonarafat** [comment]
Let me see, if it something I can work on too.

**Comment by EduardoDiNizo** [comment]
@fbernaly , @bensonarafat . Thank you very much for your attention and agility in this task. I will be the first to test the release! :)

**Comment by EduardoDiNizo** [comment]
Can I close this issue?
