### ISSUE TITLE
Idea: What about Online Machine Learning

### ISSUE THREAD

**Issue by AndreaPrati98** [flutter-ml/google_ml_kit_flutter#449]
Hi,

I would like to propose an idea to you. It could be great to implement some basic [Online Machine Learning](https://en.wikipedia.org/wiki/Online_machine_learning) models.

It would mean to use less memory and to enable the development of application for IoT and smart home application.

What do you think about it?

:)

**Comment by fbernaly** [comment]
@AndreaPrati98: great idea, fork our repo, work on your idea, submit the PR, I will review and merge, and release ASAP. Contributions are always welcome.

**Comment by fbernaly** [comment]
I think that is not supported by https://developers.google.com/ml-kit
