### ISSUE TITLE
PlatformException (PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException:

### ISSUE THREAD

**Issue by HumzaKhan071** [flutter-ml/google_ml_kit_flutter#450]
PlatformException (PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1)., null, null))

**Comment by fbernaly** [comment]
Could you provide more detail? or close for inactivity

**Comment by kapil708** [comment]
Is there any update I having the same problem.

**Comment by HumzaKhan071** [comment]
Yes i published an article for this. You can get help from this


https://link.medium.com/AcXM3sYykCb
