### ISSUE TITLE
[entity extraction] `time` does not set reference time when annotating text

### ISSUE THREAD

**Issue by RomainFranceschini** [flutter-ml/google_ml_kit_flutter#452]
`EntityExtractor.annotateText` documentation specifies the `time` parameter is used to set a reference time for extracting relative dates, however both iOS and Android plugin implementation does not pass this parameter to ML Kit.

**Comment by fbernaly** [comment]
@RomainFranceschini : thanks for the contribution, I will release later this week. In the meantime you can update your yaml file using git pointing to master
