### ISSUE TITLE
google_mlkit_text_recognition need Text.Symbol class

### ISSUE THREAD

**Issue by huage2580** [flutter-ml/google_ml_kit_flutter#457]
hi, thanks for your work for this helpful lib.

Is it possible add the `Text.Symbol`  in `google_mlkit_text_recognition` ?

the document link:

[Text.Element#getSymbols()](https://developers.google.com/android/reference/com/google/mlkit/vision/text/Text.Element#getSymbols())

[Text.Symbol](https://developers.google.com/android/reference/com/google/mlkit/vision/text/Text.Symbol)

**Comment by huage2580** [comment]
I realize that mlkit doesn't provide a method for symbol on ios.

so we need to wait ...

https://developers.google.com/ml-kit/reference/swift/mlkittextrecognitioncommon/api/reference/Classes/TextElement

**Comment by fbernaly** [comment]
@huage2580 : in this PR I am adding TextSymbol for Android, for iOS it will return an empty array: https://github.com/flutter-ml/google_ml_kit_flutter/pull/459
I hope that helps. I do not know when Google will update their native API/
