### ISSUE TITLE
Semantic Issue (Xcode): Property 'confidence' not found on object of type 'MLKTextLine *'

### ISSUE THREAD

**Issue by dwzrlp** [flutter-ml/google_ml_kit_flutter#458]
Semantic Issue (Xcode): Property 'confidence' not found on object of type 'MLKTextLine *'
/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/GoogleMlKitTextRecognitionPlugin.m:130:35

Semantic Issue (Xcode): Property 'angle' not found on object of type 'MLKTextLine *'
/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/GoogleMlKitTextRecognitionPlugin.m:131:35

Semantic Issue (Xcode): Property 'confidence' not found on object of type 'MLKTextElement *'
/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/GoogleMlKitTextRecognitionPlugin.m:142:42

Semantic Issue (Xcode): Property 'angle' not found on object of type 'MLKTextElement *'
/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/GoogleMlKitTextRecognitionPlugin.m:143:42

**Comment by bensonarafat** [comment]
Hmm, 
confidence score not found in IOS. 
https://developers.google.com/ml-kit/reference/ios/mlkittextrecognitioncommon/api/reference/Classes/MLKTextLine

**Comment by fbernaly** [comment]
I am working on a hotfix... will release in a couple hours

**Comment by nilekell** [comment]
I'm also having this issue, with the stack trace:

```
flutter run
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...                                           2,461ms
Running Xcode build...                                                  
Xcode build done.                                            7.7s
Failed to build iOS app
Semantic Issue (Xcode): Property 'confidence' not found on object of type 'MLKTextLine *'
/Users/nile/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/Googl
eMlKitTextRecognitionPlugin.m:130:35


Semantic Issue (Xcode): Property 'angle' not found on object of type 'MLKTextLine *'
/Users/nile/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/Googl
eMlKitTextRecognitionPlugin.m:131:35


Semantic Issue (Xcode): Property 'confidence' not found on object of type 'MLKTextElement
*'
/Users/nile/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/Googl
eMlKitTextRecognitionPlugin.m:142:42


Semantic Issue (Xcode): Property 'angle' not found on object of type 'MLKTextElement *'
/Users/nile/.pub-cache/hosted/pub.dev/google_mlkit_text_recognition-0.7.0/ios/Classes/Googl
eMlKitTextRecognitionPlugin.m:143:42


Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
```

**Comment by fbernaly** [comment]
This fixes this issue: https://github.com/flutter-ml/google_ml_kit_flutter/pull/459

**Comment by fbernaly** [comment]
Upgrade `google_mlkit_text_recognition` to https://pub.dev/packages/google_mlkit_text_recognition/versions/0.8.0
