### ISSUE TITLE
Update to google_mlkit_text_recognition: ^0.8.0

### ISSUE THREAD

**Issue by Zaoldyek** [flutter-ml/google_ml_kit_flutter#460]
we need the update with google_mlkit_text_recognition: ^0.8.0

![image](https://github.com/flutter-ml/google_ml_kit_flutter/assets/16231201/4d9c4ca0-a152-4d37-82c2-786d31912ba7)

**Comment by fbernaly** [comment]
Duplicates https://github.com/flutter-ml/google_ml_kit_flutter/issues/458

Try: google_mlkit_text_recognition: ^0.8.1

https://pub.dev/packages/google_mlkit_text_recognition/versions/0.8.1

**Comment by Zaoldyek** [comment]
Hello, 
When I try to use google mlkit text recognition I throwt the following error
![image](https://github.com/flutter-ml/google_ml_kit_flutter/assets/16231201/562df62f-69b7-4ca3-ac41-1164b5579e1c)

**Comment by fbernaly** [comment]
You need to resolve your dependencies, that is the error. If you are using text recognition you need to remove the umbrella plugin: google_ml_kit. Check our readme
