### ISSUE TITLE
flutter: Calculator::Open() for node "ClassifierClientCalculator" failed: #vk The input tensor should have dimensions 1 x height x width x 3. Got 1 x 3 x 416 x 416., null)

### ISSUE THREAD

**Issue by azazadev** [flutter-ml/google_ml_kit_flutter#461]
I'm trying to run custom model for label_detector use case, and I'm using the same [example](https://github.com/flutter-ml/google_ml_kit_flutter/blob/b55839afca729ce0d4429b8d3ac87d5abdc10a9d/packages/example/lib/vision_detector_views/label_detector_view.dart#L73) to load model and process image, but I got this error : **The input tensor should have dimensions 1 x height x width x 3. Got 1 x 3 x 416 x 416., null)**

```
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
flutter: ERROR: PlatformException(Error 3, com.google.visionkit.pipeline.error, Pipeline failed to fully start:
flutter: CalculatorGraph::Run() failed in Run:
flutter: Calculator::Open() for node "ClassifierClientCalculator" failed: #vk The input tensor should have dimensions 1 x height x width x 3. Got 1 x 3 x 416 x 416., null)
flutter:
flutter: STACK:#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
flutter: #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
flutter: <asynchronous suspension>
flutter: #2      ImageLabeler.processImage (package:google_mlkit_image_labeling/src/image_labeler.dart:20:20)
```

how I can preprocess image to make it compatible with the model ? should I do something on model ?

**Comment by fbernaly** [comment]
Check [TensorFlow Lite model compatibility](https://developers.google.com/ml-kit/custom-models#model-compatibility) to learn how to make your model compatible with ML Kit.
I was playing with custom model as well and created this tutorial to document my finds: https://github.com/flutter-ml/mlkit-custom-model
I think you need to make sure the metadata in your input tensor meets the [compatibility requirements from ML Kit](https://developers.google.com/ml-kit/custom-models#model-compatibility).
