### ISSUE TITLE
Custom model unable to detect objects 

### ISSUE THREAD

**Issue by fransay** [flutter-ml/google_ml_kit_flutter#463]
Hi family, I have got a customed tflite model generate from the tensorflow object detection API, I am trying to run inference on an image  using the google_ml_toolkit object detection package.  An inference returns no ouput, however when I try running the use an example model in trained for recognition birds in the example folder, it does work. Counting on your help and assistance.
 Looking forward to get assistance on information regarding what models what are compatible and those which are not.

**Comment by fbernaly** [comment]
Check [TensorFlow Lite model compatibility](https://developers.google.com/ml-kit/custom-models#model-compatibility) to learn how to make your model compatible with ML Kit.
I was playing with custom model as well and created this tutorial to document my finds: https://github.com/flutter-ml/mlkit-custom-model
I think you need to make sure the metadata in your input tensor meets the [compatibility requirements from ML Kit](https://developers.google.com/ml-kit/custom-models#model-compatibility).
