### ISSUE TITLE
NV21 to JPG

### ISSUE THREAD

**Issue by ranulfo** [flutter-ml/google_ml_kit_flutter#465]
how do i convert NV21 to jpg?

Before, in the older version that gave me the image in YUV, I did the conversion to JPG using dart's own "image" package. now with this version that generates the image in NV21 and I can no longer use the same conversion method, can anyone help me?
previously used method:

`static Future<List<int>> convertCameraImageToImage(
      CameraImage cameraImage) async {
    if (Platform.isAndroid) {
      final DynamicLibrary convertImageLib = Platform.isAndroid
          ? DynamicLibrary.open("libconvertImage.so")
          : DynamicLibrary.process();

      _conv = convertImageLib
          .lookup<NativeFunction<convert_func>>('convertImage')
          .asFunction<Convert>();
    }

    //ranulfo - 20230615 - início

    imglib.Image? img;
    if (Platform.isAndroid) {
      Pointer<Uint8> p = calloc(cameraImage.planes[0].bytes.length);
      Pointer<Uint8> p1 = calloc(cameraImage.planes[1].bytes.length);
      Pointer<Uint8> p2 = calloc(cameraImage.planes[2].bytes.length);

      // Assign the planes data to the pointers of the image
      Uint8List pointerList = p.asTypedList(cameraImage.planes[0].bytes.length);
      Uint8List pointerList1 =
          p1.asTypedList(cameraImage.planes[1].bytes.length);
      Uint8List pointerList2 =
          p2.asTypedList(cameraImage.planes[2].bytes.length);
      pointerList.setRange(
          0, cameraImage.planes[0].bytes.length, cameraImage.planes[0].bytes);
      pointerList1.setRange(
          0, cameraImage.planes[1].bytes.length, cameraImage.planes[1].bytes);
      pointerList2.setRange(
          0, cameraImage.planes[2].bytes.length, cameraImage.planes[2].bytes);

      // Call the convertImage function and convert the YUV to RGB
      Pointer<Uint32> imgP = _conv(
          p,
          p1,
          p2,
          cameraImage.planes[1].bytesPerRow,
          cameraImage.planes[1].bytesPerPixel!,
          cameraImage.width,
          cameraImage.height);
      // Get the pointer of the data returned from the function to a List
      List<int> imgData =
          imgP.asTypedList((cameraImage.width * cameraImage.height));

      //ranulfo 20230615 - inicio
      Uint8List uint8List = Uint8List.fromList(imgData);
      ByteBuffer byteBuffer = uint8List.buffer;
      //ranulfo 20230615 - fim

      img = imglib.Image.fromBytes(
          height: cameraImage.height,
          width: cameraImage.width,
          bytes: byteBuffer /*imgData*/);

      calloc.free(p);
      calloc.free(p1);
      calloc.free(p2);
      calloc.free(imgP);
      img = imglib.flip(img, direction: imglib.FlipDirection.vertical);
    } else if (Platform.isIOS) {
      img = imglib.Image.fromBytes(
        //cameraImage.planes[0].bytesPerRow,
        width: cameraImage.width,
        height: cameraImage.height,
        bytes: cameraImage.planes[0].bytes.buffer,
        format: imglib.Format.bgra, //ranulfo 20230615
      );
    }
    var imgJpg = imglib.encodeJpg(img!, quality: 70);
   
    return imgJpg;
  }`

**Comment by fbernaly** [comment]
This plugin does not provide conversion from CameraImage or InputImage to JPG.

However, I hope this helps: NV21 has only 1 plane, and YUV 3, try to use the same plane for the others or convert it with a single plane like in iOS. Basically NV21 and BGRA8888 are the same in terms of having a single plane, you can use `_convertBGRA8888` like in this post: https://gist.github.com/Alby-o/fe87e35bc21d534c8220aed7df028e03

**Comment by ranulfo** [comment]
I already tried to use this method for nv21 images and it **doesn't work**. but it is worth remembering that in the new version of image.dart `image: ^4.0.17`, the `fromBytes` method was changed and the bytes parameter now expects a `ByteBuffer` type and the `format` parameter is now an enum of type:


```
enum Format {
  uint1,
  uint2,
  uint4,
  uint8,
  uint16,
  uint32,
  int8,
  int16,
  int32,
  float16,
  float32,
  float64
}
```


causing the call to result in an error

```
var img = imglib.Image.fromBytes(
      width: cameraImage.width,
      height: cameraImage.height,
      bytes: cameraImage.planes[0].bytes.buffer,
      format: imglib.Format.uint8, 
    );
```
    
`RangeError (RangeError (end): Invalid value: Not in inclusive range 518400..518586: 520560) `

**Comment by ranulfo** [comment]
Please, reopen this issue

**Comment by fbernaly** [comment]
@ranulfo: you issue is outside of our scope, you are trying to convert CameraImage to Image, and those classes belong to other plugins, I recommend you go to the repos for those plugins and post your issue there: How to convert CameraImage to Image when using nv21.

**Comment by vietvmq** [comment]
You can use this [convert_native_img_stream](https://pub.dev/packages/convert_native_img_stream) to convert. It work so well.
