### ISSUE TITLE
Is Supported FaceDeteced Device

### ISSUE THREAD

**Issue by tungbnt** [flutter-ml/google_ml_kit_flutter#467]
I want to check if the device supports face recognition when the camera is not open. Thank you everyone and look forward to your comments

**Comment by fbernaly** [comment]
You need to pass an `InputImage` to the face detector or to any vision detector, you can get the image from the camera or from a file/asset (not using the camera).

Look at this: 
https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage
https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_face_detection#create-an-instance-of-inputimage

I hope that answers your question.

**Comment by tungbnt** [comment]
I really appreciate your ideas. but it's not ok when i give an image the gallery recognizes the face. What I want to aim for is to check if the device can detect faces before being in the camera that still can't be processed. Hope to get a response from you.

**Comment by tungbnt** [comment]
> You need to pass an `InputImage` to the face detector or to any vision detector, you can get the image from the camera or from a file/asset (not using the camera).
> 
> Look at this: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_face_detection#create-an-instance-of-inputimage
> 
> I hope that answers your question.

Because, I think when adding images other than taking pictures from the phone's camera, the gallery is still detectable easily.

**Comment by fbernaly** [comment]
I am not sure if I am getting what you want to do, but: the only way that faces will be detected is when you pass InputImages to the detector. Other than that there is not other way.

**Comment by tungbnt** [comment]
my wish is to detect a mobile device with hardware that does not support face without opening the camera or giving inputimage. Thank you very much @fbernaly.
