### ISSUE TITLE
InputPlaneImageMetadata deprecated?

### ISSUE THREAD

**Issue by mikhael28** [flutter-ml/google_ml_kit_flutter#475]
Why is the plane ImageMetadata marked as deprecated in newer releases after 0.6.0? Was it replaced with a similarly named class? I'm not seeing it in the documentation, maybe I'm being blind? I want to keep the way that the image metadata can be superimposed over the screen.

**Comment by fbernaly** [comment]
Yes, we updated the API in this PR: https://github.com/flutter-ml/google_ml_kit_flutter/pull/454
 
We updated the README as well: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage

and the example app: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/camera_view.dart#L320-L396

I hope that helps you to migrate to the latest version.

**Comment by mikhael28** [comment]
You are amazing, sorry for my fumbling question.

**Comment by fbernaly** [comment]
No problem. Actually I just published a new version and updated the README with more details. It will be all in master once we merge this PR: https://github.com/flutter-ml/google_ml_kit_flutter/pull/480
