### ISSUE TITLE
google face ml kit needs to have .startVideoRecord() instead of .startImageStream.

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter-ml/google_ml_kit_flutter#479]
Actually my usecase is to implement liveness detection using facekit, but i need to save the whole process video of user. Will u able to help?

**Comment by fbernaly** [comment]
Please read the first section of this plugin on how this plugin is build using Method Channels. This plugin is a mirror of the functionality that Google offers in the native [ML Kit for iOS and Android](https://developers.google.com/ml-kit/guides).
Recording video is outside the scope of this plugin.
If you want to record video try the [camera plugin](https://pub.dev/packages/camera), with that you can record and the process the video with our plugin.
Our plugin takes an [InputImage](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_commons/lib/src/input_image.dart). The inputImage can be generated from a file or from a camera stream.
I hope that helps.
