### ISSUE TITLE
null objc class data for '_OBJC_METACLASS_$MLKXXX' in $path

### ISSUE THREAD

**Issue by wenhehu** [flutter-ml/google_ml_kit_flutter#484]
Error (Xcode): Multiple errors: null objc class data for '_OBJC_METACLASS_$_MLKIdentifiedLanguage' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitLanguageID/Frameworks/MLKitLanguageID.framework/MLKitLanguageID'; null objc class data for '_OBJC_METACLASS_$_MLKDateTimeEntity' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitEntityExtraction/Frameworks/MLKitEntityExtraction.framework/MLKitEntityExtraction'; null objc class data for '_OBJC_METACLASS_$_MLKSmartReply' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitSmartReply/Frameworks/MLKitSmartReply.framework/MLKitSmartReply'; null objc class data for '_OBJC_METACLASS_$_MLKBarcode' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning'; null objc class data for '_OBJC_METACLASS_$_MLKFace' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitFaceDetection/Frameworks/MLKitFaceDetection.framework/MLKitFaceDetection'; null objc class data for '_OBJC_METACLASS_$_MLKDigitalInkRecognitionCandidate' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitDigitalInkRecognition/Frameworks/MLKitDigitalInkRecognition.framework/MLKitDigitalInkRecognition'; null objc class data for '_OBJC_METACLASS_$_MLKInternalAsyncProcessImageResult' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitXenoCommon/Frameworks/MLKitXenoCommon.framework/MLKitXenoCommon'; null objc class data for '_OBJC_METACLASS_$_MLKMutableRemoteModel' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitTranslate/Frameworks/MLKitTranslate.framework/MLKitTranslate'; null objc class data for '_OBJC_METACLASS_$_MLKVisionKitError' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitVisionKit/Frameworks/MLKitVisionKit.framework/MLKitVisionKit'; null objc class data for '_OBJC_METACLASS_$_MLKCommonTextRecognizerOptions' in '/Users/gege/Desktop/dev/google_ml_kit_flutter/packages/example/ios/Pods/MLKitTextRecognitionCommon/Frameworks/MLKitTextRecognitionCommon.framework/MLKitTextRecognitionCommon'

**Comment by fbernaly** [comment]
Try example app.

**Comment by fbernaly** [comment]
Did you run `pod install`?

**Comment by wenhehu** [comment]
> Did you run `pod install`?

Yes

**Comment by wenhehu** [comment]
> Try example app, and provide details of your issue, otherwise we cannot help and will close issue.
environment：
Xcode Version 15.0 beta 3 (15A5195k)
CocoaPods version 1.12.1
Flutter (Channel stable, 3.10.5, on macOS 14.0 23A5286g darwin-x64, locale zh-Hans-CN)
Dart version 3.0.5

**Comment by fbernaly** [comment]
I am using:

macOS Ventura 13.4.1
Xcode Version 14.2 (14C18)
CocoaPods version 1.12.1

Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] Network resources
```

Remove your `Pods` folder: `google-ml-kit-plugin/packages/example/ios/Pods`

and run `./update_libs.sh` in the [root directory](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/update_libs.sh).

Example app is okay, you need to check your local environment.

I noticed that you are using the Xcode beta version, I am not sure if that is the issue. I am using the latest official stable.

**Comment by chris-pcv** [comment]
For those who still have issues with Xcode 15 (beta), adding `-ld64` to "Other Linker Flags" worked for me (https://developer.apple.com/forums/thread/731089).

**Comment by fbernaly** [comment]
Thanks @chris-pcv, I will add that to the README.

Could other confirm that this is fixing their issue as well.

**Comment by binc0** [comment]
I had same issue and fixed as described.

> For those who still have issues with Xcode 15 (beta), adding `-ld64` to "Other Linker Flags" worked for me (https://developer.apple.com/forums/thread/731089).
