### ISSUE TITLE
google_mlkit_barcode_scanning returns old result when is opened second time

### ISSUE THREAD

**Issue by tavyDesign** [flutter-ml/google_ml_kit_flutter#488]
After first scan, when camera is opened second time, it return last code scanned.

I found something similar here: https://stackoverflow.com/questions/73538063/flutter-ml-kit-barcodescanner-returns-old-result-how-do-i-stop-this

**Comment by fbernaly** [comment]
@tavyDesign : please send a PR with your contribution
