### ISSUE TITLE
barcode_scanner crash

### ISSUE THREAD

**Issue by ram-niwas1997** [flutter-ml/google_ml_kit_flutter#490]
../../flutter/.pub-cache/hosted/pub.dartlang.org/google_mlkit_barcode_scanning-0.8.0/lib/src/barcode_scanner.dart:207:9: Error: 'Uint8List' isn't a type.
  final Uint8List rawBytes;
        ^^^^^^^^^
../../flutter/.pub-cache/hosted/pub.dartlang.org/google_mlkit_barcode_scanning-0.8.0/lib/src/barcode_scanner.dart:210:9: Error: 'Rect' isn't a type.
  final Rect boundingBox;
        ^^^^
![Screenshot 2023-07-20 at 5 10 28 PM](https://github.com/flutter-ml/google_ml_kit_flutter/assets/130345407/4e9de504-d274-420e-a219-b6d91c63cccc)

**Comment by fbernaly** [comment]
@ram-niwas1997: could you provide a QR code example where the `boundingBox` is null or te one you use to throw this error.

**Comment by ram-niwas1997** [comment]
when I import this plugin => google_ml_kit: ^0.16.1  then this above error occur.

**Comment by fbernaly** [comment]
@ram-niwas1997 : did it crash when you scan the QR code or just by importing the plugin without scanning?
If the crash happens when you scan, please share the QR code, otherwise I wont be able to help you.

**Comment by fbernaly** [comment]
Fix in PR: https://github.com/flutter-ml/google_ml_kit_flutter/pull/500

**Comment by vinhmdev** [comment]
Me too, do you have any solution for this issue?

**Comment by fbernaly** [comment]
yes, it was included in: [google_mlkit_barcode_scanning v0.9.0](https://pub.dev/packages/google_mlkit_barcode_scanning/changelog#090)
