### ISSUE TITLE
[google_mlkit_entity_extraction] iOS and Android detect different timestamps 

### ISSUE THREAD

**Issue by test0terter0n** [flutter-ml/google_ml_kit_flutter#492]
As I played around with the example app, I might found a bug trying to convert timestamp to DateTime.

On Android `25 Jul` from the Screenshot below has timestamp: `1690236000000`. This is the expected value.
On iOS  timestamp of `25 Jul` has timestamp 1690236000.

As a workaround I multiply timestamp values on iOS with 1000, but it would be nice if this can be fixed.

![IMG_3476](https://github.com/flutter-ml/google_ml_kit_flutter/assets/48948613/c2c300fb-e26d-4b4f-8763-2826a9eb78da)

**Comment by fbernaly** [comment]
@test0terter0n : this is an open source project, contributions are welcome. Feel free to send a PR with your contribution. Since you have already found the bug and know how to reproduce it, please go ahead and send us a PR.

**Comment by test0terter0n** [comment]
@fbernaly  did create https://github.com/flutter-ml/google_ml_kit_flutter/pull/501
