### ISSUE TITLE
Coordinate System Applied In Text Recognition Engine

### ISSUE THREAD

**Issue by fransay** [flutter-ml/google_ml_kit_flutter#507]
Hi contributors, 

Thanks so much for the tremendous effort in developing this toolkit, it awesome!

The text recognition package is just beautiful and works with accuracy and speed as I wish, 

It does well returning a list of coordinates(Corner points) of the bounding box of each TextBlock, TextLine or even an Element 

I am very interested in  understanding the underlying coordinate system of which these corner points are referenced.
 
For example an element might have cornerpoints like this [(550,234), (453,245), (500, 240),(510, 245)].
 
Now the question what kind/type of kind of coordinate system are these cornerpoints based, eg. Standard Cartesian, Standard Image Coordinate System, etc.

if it is different, how different it is from the from the **Standard Image Coordinate System**, where the origin is at the top left corner of the image. 
 
Each assistance towards this will be highly appreciated. 
 
Many thanks!

**Comment by fbernaly** [comment]
The coordinates are using the standard image coordinate system. If you look at the documentation you will find that:
iOS: https://developers.google.com/ml-kit/reference/swift/mlkittextrecognitioncommon/api/reference/Classes/TextBlock#cornerpoints
Android: https://developers.google.com/android/reference/com/google/mlkit/vision/text/Text.TextBlock#public-point[]-getcornerpoints
And we are passing that to Flutter.
However, you need to consider the image rotation, in particular for Android, it varies if you are using back for front camera, as well as the sensor orientation. I have added this in the [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage), look for how `InputImageRotation? rotation` is computed. You need to pass that when you call `InputImage.fromBytes`.
Then, when you receive the response from the text detector you will get the corner points (which are in standard/default image coordinate system), but you need to rotate them to correspond with the image rotation computed when you created the instance of InputImage.
Follow the example app:
1. When the text detector response is received, we are passing the recognized text, size and rotation to a `Painter` ([TextRecognizerPainter](https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/painters/text_detector_painter.dart)).  TextRecognizerPainter is a subclass of [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter-class.html) used to paint a rect for the corresponding corner points for each text block.
2. In the  class you will see that the corner point are translated using imageSize, canvasSize, rotation and camaraLensDirection (I know, too many things, but all of them are needed): https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/painters/text_detector_painter.dart#L81-L159
3. In this file I have implemented the methods to translated X and Y: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/painters/coordinates_translator.dart
4. Once you translate x and y for each corner point then you can draw the array in the canvas: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/painters/text_detector_painter.dart#L159-L164
Take a look at our example app for more details on how this is implemented, I have throughly tested this for both Android and iOS and I am confident that with those methods you can get the corner points correctly regardless of the platform, rotation, camera lens directions, etc.

I hope this helps.

**Comment by fransay** [comment]
Yes, it does.
Many thanks.

**Comment by fbernaly** [comment]
Thanks for asking, I just realized that I forgot to include that in the README, but it is in the example app: https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/camera_view.dart#L320-L325

It is a dictionary that maps `DeviceOrientation` enum to an `int`

```
final _orientations = {
  DeviceOrientation.portraitUp: 0,
  DeviceOrientation.landscapeLeft: 90,
  DeviceOrientation.portraitDown: 180,
  DeviceOrientation.landscapeRight: 270,
};
```

**Comment by fransay** [comment]
You are the best. I am gradually getting hold of your beautiful creation. I hope, I am able to get the cornerpoints rotated successfully to work with the the InputImage instance prior entry to the text detector. I will ping you here when I face any doubt or challenge.
Thanks a lot Francis!
