### ISSUE TITLE
Using InputImage.bgra8888 on Android not working in textRecognizer?

### ISSUE THREAD

**Issue by AndreasAny** [flutter-ml/google_ml_kit_flutter#508]
Hi folks,

im trying to convert the annoying nv21-Format to bgra8888, before passing it to the textRecognizer.

Following Code: 

`  Future<void> processImage(InputImage inputImage, CameraImage camImage, int threadNum) async {
    
    if (_isBusy) return;

    inputImage = ImageConvertCustom.convertNV21toBGRA8888InputImage(inputImage);

    final recognizedText = await textRecognizer.processImage(inputImage);

    //...`

Iam on Android and the InputImage comes in NV21. Then I put it through the following code:

`static InputImage convertNV21toBGRA8888InputImage(InputImage inputImage) {

    Uint8List rgbData = convertNV21toRGB((inputImage.bytes!).buffer.asUint8List(), inputImage.metadata!.size.width.toInt(), inputImage.metadata!.size.height.toInt());

    Uint8List bgraData = convertRGBtoBGRA(rgbData);

    InputImageMetadata newMeta = InputImageMetadata(size: inputImage.metadata!.size, rotation: inputImage.metadata!.rotation, format: InputImageFormat.bgra8888, bytesPerRow: inputImage.metadata!.size.width.toInt());

    InputImage newImage = InputImage.fromBytes(bytes: bgraData, metadata: newMeta);

    return newImage;

  }`

The definition of the used functions is:

`static Uint8List convertRGBtoBGRA(Uint8List rgbData) {
    if (rgbData.length % 3 != 0) {
      throw ArgumentError("RGB data length must be a multiple of 3.");
    }

    int numPixels = rgbData.length ~/ 3;
    Uint8List bgraData = Uint8List(numPixels * 4);

    for (int i = 0; i < numPixels; i++) {
      int r = rgbData[i * 3];
      int g = rgbData[i * 3 + 1];
      int b = rgbData[i * 3 + 2];

      bgraData[i * 4] = b;     // Blue channel
      bgraData[i * 4 + 1] = g; // Green channel
      bgraData[i * 4 + 2] = r; // Red channel
      bgraData[i * 4 + 3] = 255; // Alpha channel (fully opaque)
    }

    return bgraData;
  }`

`static Uint8List convertNV21toRGB(Uint8List nv21Data, int width, int height) {
    Uint8List rgbData = Uint8List(width * height * 3);

    int imageSize = width * height;

    for (int j = 0; j < height; j++) {
      int startY = j * width;
      int uvRowOffset = imageSize + (j >> 1) * width;

      for (int i = 0; i < width; i++) {
        int uvOffset = uvRowOffset + (i & ~1);
        int y = nv21Data[startY + i];
        int u = nv21Data[uvOffset];
        int v = nv21Data[uvOffset + 1];

        int r, g, b;

        // YUV to RGB conversion
        r = (y + (1.370705 * (v - 128))).toInt();
        g = (y - (0.698001 * (v - 128)) - (0.337633 * (u - 128))).toInt();
        b = (y + (1.732446 * (u - 128))).toInt();

        r = r.clamp(0, 255);
        g = g.clamp(0, 255);
        b = b.clamp(0, 255);

        int rgbOffset = (j * width + i) * 3;
        rgbData[rgbOffset] = r;
        rgbData[rgbOffset + 1] = g;
        rgbData[rgbOffset + 2] = b;
      }
    }

    return rgbData;
  }`

When I give the InputImage in the new bgra-Format to the recognizer, it recognizes nothing. May be that die Data are corrupted? But i did check this by converting the Bytes from the Input-Image in bgra to jpeg and display the result in an MemoryImage-Widget. The Image shows correctly. So why does the recognizer dont recognize? :)

Maybe is that because the model on android is different from the one for Iphone, and it have to be a NV21?

I really run out of ideas why this isnt working.

**Comment by fbernaly** [comment]
Why are you converting nv21 to bgra8888?
Did you read our README? Here is how you create the InputImage: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage
You need to pass nv21 for Android and bgra8888 for iOS, you do not need to make any conversion, a different format is expected for each platform. Look at our README and example app to learn how to setup correctly your CameraController.
* https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_commons#creating-an-inputimage
* https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/example/lib/vision_detector_views/camera_view.dart

**Comment by AndreasAny** [comment]
Ok thx I see. I was hoping to simply can use both formats by converting the bytes and create a new InputImage with the right metadata.

I have a lot of trouble when it comes to manipulate the NV21-Bytes for rotation, cropping and filling up black pixels to save performance for the ocr. I only want to send a part of the Image to the OCR and try to fill that cropped part with black pixels, so the coordinates of blocks, lines and elements stay correctly. When i use the functions I collected to manipulate the bytes, the result of the nv21-image is always greenish, sometimes not readable anymore.

**Comment by fbernaly** [comment]
When cropping the image make sure you conform with the Input image guidelines, in particular the size.
https://developers.google.com/ml-kit/vision/text-recognition/v2/android#input_image_guidelines
