### ISSUE TITLE
How to get the element text when tapped on text detector view?

### ISSUE THREAD

**Issue by j007ha** [flutter-ml/google_ml_kit_flutter#511]
Hi all guru,

I would like to get the element text value while user tap on the green bounding box while scanning. I'm not able to determine whether the tapped coordinates is within the bounding box.

Currently i'm using TapDownDetails localPosition.dx and dy to check is it fall within the boundary but it is not working. Appreciate if anyone can advise on this.

**Comment by j007ha** [comment]
Code as below:

`_onTapDown(TapDownDetails details) {
    var x = details.localPosition.dx;
    var y = details.localPosition.dy;

    for (int i = 0; i < recognizedText.blocks.length; i++) {
      var block = recognizedText.blocks[i];

      for (int j = 0; j < block.lines.length; j++) {
        var line = block.lines[j];

        for (int k = 0; k < line.elements.length; k++) {
          var element = line.elements[k];
          var box = element.boundingBox;

          if (element.boundingBox.contains(new Offset(x, y))) {
            sleep(Duration(milliseconds: 150));
            print(element.text);
            //Navigator.pop(context, element.text);
            break;
          }
        }
      }
    }
  }`

**Comment by fbernaly** [comment]
@j007ha: this plugin will only return the recognized text with the corner points or bounding box. It is outside the scope of this plugin to handle tapping on the image and detecting the area you tapped.
This is similar to issue: https://github.com/flutter-ml/google_ml_kit_flutter/issues/186.
