### ISSUE TITLE
Face Detection Problem

### ISSUE THREAD

**Issue by ShoaibAkhtar23** [flutter-ml/google_ml_kit_flutter#514]
The face is not detected when the device is in a landscape position.

**Comment by fbernaly** [comment]
Did you try the example app? Could you reproduce with the example app?

**Comment by ShoaibAkhtar23** [comment]
Yes, I have tried the example app.

**Comment by fbernaly** [comment]
are you sure? are you running the app on iOS or Android?

These are screenshoots from our example app:

**back_landscape**:
![back_landscape](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/b0bb3a2c-cc5c-4b93-a294-f40c5f858093)

**back_portrait**:
![back_portrait](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/478edd6b-83cd-4812-a0a5-e2b1fabc4fdc)

**front_landscape**:
![front_landscape](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/24fadeab-6f71-4db9-8562-e71613b56bd8)

**front_portrait**:
![front_portrait](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/1ce6e697-2a08-4664-98b5-3bd3a3dc9734)

**Comment by ShoaibAkhtar23** [comment]
Oh, It's my mistake. I lock the phone in the portrait position. Thanks for your help.
