### ISSUE TITLE
Save Scanned Frame as Image in PNG or JPG.

### ISSUE THREAD

**Issue by MMoarales** [flutter-ml/google_ml_kit_flutter#515]
Hi, I'm using google_ml_kit_flutter to recognize text in real-time, but I need to save the frame used in the process. I tried some different ways but no results. Is it possible to get the image?

**Comment by fbernaly** [comment]
If you are using the `camera` plugin then you need to save `CameraImage`, that is outside of the scope of this plugin. `CameraImage` belongs to `camera` plugin.
However, here is what I would do: there at least to ways you can approach this:
* Follow the conversation in this thread: https://gist.github.com/alby-o/fe87e35bc21d534c8220aed7df028e03. They offered a couple of methods to covert the CameraImage to Image and save it to a file.
* Use `CameraController` to take a picture: https://github.com/flutter/packages/blob/main/packages/camera/camera/lib/src/camera_controller.dart#L412

I hope that helps.
