### ISSUE TITLE
How to capture the faces detected by this API?

### ISSUE THREAD

**Issue by ShoaibAkhtar23** [flutter-ml/google_ml_kit_flutter#517]
Is it possible to capture the faces detected by this API and then display those captured images on another screen?

**Comment by fbernaly** [comment]
Technically it is possible, but it is outside the scope of this plugin.
This plugin will return the corner point or the bounding rect and then you can crop the CameraImage using those corner point or bounding rect, but that is something the client app consuming this plugin needs to do. Good luck.
