### ISSUE TITLE
Crash on multiple usage of TextRecognizer

### ISSUE THREAD

**Issue by kyeshmz** [flutter-ml/google_ml_kit_flutter#519]
I have a piece of information that is listed in 2 different languages.
I need to extract the Japanese information as well as the English information.

Currently, this package crashes on the initialization of 2 or more TextRecognizer()s.
Is there a way to get a more detailed error?
Currently, this is only thing that I can get info from. 

```
E/AndroidRuntime(29369): FATAL EXCEPTION: pool-24-thread-2
E/AndroidRuntime(29369): Process: io.nanco.staging, PID: 29369
E/AndroidRuntime(29369): java.lang.AbstractMethodError: abstract method "java.lang.String com.google.mlkit.vision.text.TextRecognizerOptionsInterface.getConfigLabel()"
E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.zzc.zzd(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:2)
E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.zzc.zzb(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:9)
E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.load(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:1)
E/AndroidRuntime(29369): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.8.0:4)

```

**Comment by bensonarafat** [comment]
@kyeshmz 
thanks for the error log

**Comment by kyeshmz** [comment]
I was able to get around this by  adding the dynamic feature support. Is this something needed to be documented or just something completely different?
```
dependencies {
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.0   -beta6'
    implementation 'com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2'
```

**Comment by Rishab-ms** [comment]
@kyeshmz Could you explain more about this workaround? How does it work?

**Comment by kyeshmz** [comment]
@Rishab-ms It is simply adding both the dynamic feature support and also the language you need. But it might also just have been a corruption of my simulator env.

**Comment by pksunny** [comment]
> I have a piece of information that is listed in 2 different languages. I need to extract the Japanese information as well as the English information.
> 
> Currently, this package crashes on the initialization of 2 or more TextRecognizer()s. Is there a way to get a more detailed error? Currently, this is only thing that I can get info from.
> 
> ```
> E/AndroidRuntime(29369): FATAL EXCEPTION: pool-24-thread-2
> E/AndroidRuntime(29369): Process: io.nanco.staging, PID: 29369
> E/AndroidRuntime(29369): java.lang.AbstractMethodError: abstract method "java.lang.String com.google.mlkit.vision.text.TextRecognizerOptionsInterface.getConfigLabel()"
> E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.zzc.zzd(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:2)
> E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.zzc.zzb(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:9)
> E/AndroidRuntime(29369): 	at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.load(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:1)
> E/AndroidRuntime(29369): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.8.0:4)
> ```

HERE"S ANSWER:

android/app/build.gradle: you have these lines of code: 

dependencies {
    // Add language package you need to use
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.0-beta6'
    implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0-beta6'
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.0-beta6'
    implementation 'com.google.mlkit:text-recognition-korean:16.0.0-beta6'
}


REPLACE WITH THIS:

implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'
implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0'
implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'
implementation 'com.google.mlkit:text-recognition-korean:16.0.0

**Comment by fbernaly** [comment]
I will update the README with this

**Comment by fa-fifi** [comment]
Any update on this issue?
