### ISSUE TITLE
Real face detection

### ISSUE THREAD

**Issue by ritunjaykumar** [flutter-ml/google_ml_kit_flutter#542]
Hi team,

I am using google_ml_kit_flutter for face detection and it is working as spectated. but How can we do so it will detect the only real faces not fake. I mean, it should detect only real human face instead of fake images(camera pic, or gallery image should not be detected).

please help me to get solution for the same

thank you

**Comment by fbernaly** [comment]
This is how Face detection works: https://developers.google.com/ml-kit/vision/face-detection

Please read how this plugin works and does in the first section of our README: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_face_detection and if you need the native API to do something different then move the conversation to Google's channel.
