### ISSUE TITLE
Issue with inconsistent/incorrect barcode scanning

### ISSUE THREAD

**Issue by bagintz** [flutter-ml/google_ml_kit_flutter#544]
Issue with inconsistent/incorrect barcode scanning

I am getting weird results on some Code 39 barcodes that start with 222.  The scanner often omits the first 2.  This happens on both my app and the example app.

Am I missing anything on making this thing be more consistent?

Thank you

**Comment by bagintz** [comment]
Here is an example that sees 2201 way more often than it sees 22201

![example](https://github.com/flutter-ml/google_ml_kit_flutter/assets/5341290/34a67811-3e4b-47e2-8769-51771b3eaf78)

**Comment by fbernaly** [comment]
@bagintz: Android or iOS? or both? have you try Google's native example app? https://github.com/googlesamples/mlkit

**Comment by bkoznov** [comment]
@fbernaly This definitely happens on iOS, and it happens on Google's native example app. This does not happen on at least two other barcode apps.

[https://pub.dev/packages/flutter_barcode_scanner](https://pub.dev/packages/flutter_barcode_scanner) Looks like this one might use AVFoundation stuff on the iOS side?
[https://pub.dev/packages/flutter_zxing](https://pub.dev/packages/flutter_zxing) And this one uses FFI with a CPP library?



![IMG_0213](https://github.com/flutter-ml/google_ml_kit_flutter/assets/59574922/b88d04df-2896-4f44-8a86-4b33a9827454)

**Comment by bagintz** [comment]
@fbernaly It *might* have something to do with code 39 having 2 ways to do checksum, mod 10 and mod 43.

**Comment by fbernaly** [comment]
@bagintz : if you can reproduce this in Google's native app then I suggest you move the conversation to Google's channels or repos. Take a look at our [README](https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_barcode_scanning) in there we explain that this plugin is only a wrapper around the native API using FlutterMethodChannels. This plugin does not process your image, it passes it to Google's native API. So, if you have issue with the native API then you need to report that to Google.
