### ISSUE TITLE
Add latest kotlin version support and fix please

### ISSUE THREAD

**Issue by fisforfaheem** [flutter-ml/google_ml_kit_flutter#547]
mpatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/Documents/ai_mockinterview/build/share_plus/.transforms/a604dea453f8f2e1ad79a7627483e5bc/transformed/out/jars/classes.jar!/META-INF/share_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/Documents/ai_mockinterview/build/fluttertoast/.transforms/f36684545ade4454e23e4c6e0863f3df/transformed/out/jars/classes.jar!/META-INF/fluttertoast_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/Documents/ai_mockinterview/build/flutter_tts/.transforms/aea02f39fff45b04cec2312d2ba95a1a/transformed/out/jars/classes.jar!/META-INF/flutter_tts_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/Documents/ai_mockinterview/build/package_info_plus/.transforms/bcdfe0fe3b690ccb784617f795424191/transformed/out/jars/classes.jar!/META-INF/package_info_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/Documents/ai_mockinterview/build/device_info_plus/.transforms/68c16cc9e4a433c107a85291686db955/transformed/out/jars/classes.jar!/META-INF/device_info_plus_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/transforms-3/faa6a3811e747950661165dfbe80d2d8/transformed/jetified-firebase-analytics-ktx-21.4.0/jars/classes.jar!/META-INF/java.com.google.android.libraries.firebase.firebase_analytics_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/transforms-3/1b5ecc174783ed1481ba3f2aa0c8cb57/transformed/jetified-firebase-auth-ktx-22.2.0/jars/classes.jar!/META-INF/java.com.google.android.libraries.firebase.firebase_auth_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/transforms-3/a2240a5f8a59d5d69e801c89609d3c3c/transformed/jetified-firebase-auth-22.2.0/jars/classes.jar!/META-INF/java.com.google.android.gmscore.integ.client.firebase-auth-api_firebase-auth-api.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/transforms-3/016ada6f1ac45fa41df1c2cce51dc979/transformed/jetified-play-services-measurement-api-21.4.0/jars/classes.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.9.10/72812e8a368917ab5c0a5081b56915ffdfec93b7/kotlin-stdlib-1.9.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e: /Users/4edoc/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.9.10/dafaf2c27f27c09220cee312df10917d9a5d97ce/kotlin-stdlib-common-1.9.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by fbernaly** [comment]
Please follow the issue template to report your issue.

**Comment by papawasher** [comment]
We have the same error facing. 

For this error:

e: /Users/4edoc/.gradle/caches/transforms-3/faa6a3811e747950661165dfbe80d2d8/transformed/jetified-firebase-analytics-ktx-21.4.0/jars/classes.jar!/META-INF/java.com.google.android.libraries.firebase.firebase_analytics_ktx_granule.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1. e:

I fixed it by adding this in your app/build.gradle

`com.google.firebase:firebase-analytics:21.5.0`

Google updated their Artifacts for maven last October 30, 2023. [here](https://developers.google.com/android/guides/releases)

and for the Firebase [here](https://firebase.google.com/support/release-notes/android#2023-10-30)

but now the only error I face is this:

C:/Users/Carlo Legara/.gradle/caches/transforms-3/90451dd29e270004f06361cbd2bcc32f/transformed/jetified-play-services-measurement-api-21.5.0-api.jar!/META-INF/java.com.google.android.gmscore.integ.client.measurement_api_measurement_api.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by fisforfaheem** [comment]
Can you help me out, as well.. I just cant understand this thing at al tried

**Comment by NghiTranVNS** [comment]
@fisforfaheem : I also got the same issue. Did you find the solution?

**Comment by wafaaHilmy** [comment]
update kotlin plugin i root gradle file to 1.9.0

 id 'org.jetbrains.kotlin.android' version '1.9.0' apply false     // Update Kotlin version here
then add in app.gradle file under kotlinOptions section the kotlin version that we need for firebase analytics
kotlinOptions {
        jvmTarget = '1.8'
        languageVersion = "1.9" // or any other compatible version with Firebase Analytics
    }

and sync ..thats it
