### ISSUE TITLE
cannot support to convert to japan language

### ISSUE THREAD

**Issue by tranquockhanh0506** [flutter-ml/google_ml_kit_flutter#549]

**Comment by uchida-masanori** [comment]
hello,
We also want to use the Japanese reading function in our Flutter app, but we found an error.
Is the error related to the Japanese plugin?
https://pub.dev/packages/google_mlkit_text_recognition/versions/0.11.0

**Comment by tranquockhanh0506** [comment]
@uchida-masanori  what's error  do you get?

**Comment by uchida-masanori** [comment]
> @uchida-masanori what's error do you get?

below is the error log.
Looks like the problem in this link to me.　https://github.com/flutter-ml/google_ml_kit_flutter/issues/519
are you also getting the same error?
```
I/DynamiteModule(21681): Considering local module com.google.mlkit.dynamite.text.japanese:10000 and remote module com.google.mlkit.dynamite.text.japanese:0
I/DynamiteModule(21681): Selected local version of com.google.mlkit.dynamite.text.japanese
E/AndroidRuntime(21681): FATAL EXCEPTION: pool-6-thread-1
E/AndroidRuntime(21681): Process: sample, PID: 21681
E/AndroidRuntime(21681): java.lang.AbstractMethodError: abstract method "java.lang.String com.google.mlkit.vision.text.TextRecognizerOptionsInterface.getConfigLabel()"
E/AndroidRuntime(21681): 	at com.google.mlkit.vision.text.internal.zzc.zzd(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:2)
E/AndroidRuntime(21681): 	at com.google.mlkit.vision.text.internal.zzc.zzb(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:9)
E/AndroidRuntime(21681): 	at com.google.mlkit.vision.text.internal.TextRecognizerTaskWithResource.load(com.google.android.gms:play-services-mlkit-text-recognition-common@@19.0.0:1)
```

**Comment by tranquockhanh0506** [comment]
did you add this code ?
dependencies {
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'
    implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'
}

**Comment by tranquockhanh0506** [comment]
@uchida-masanori btw, have you finished for ios yet?

**Comment by uchida-masanori** [comment]
> did you add this code ? dependencies { implementation 'com.google.mlkit:text-recognition-chinese:16.0.0' implementation 'com.google.mlkit:text-recognition-japanese:16.0.0' }

I added this line
`implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'`


> btw, have you finished for ios yet?

 I will try to build on ios, did you find similar errors on ios?

**Comment by tranquockhanh0506** [comment]
I don't have any errors, but I can't convert images to Japanese

**Comment by uchida-masanori** [comment]
> I don't have any errors, but I can't convert images to Japanese

thank you,  I'll try it

**Comment by uchida-masanori** [comment]
> thank you, I'll try it

I read Japanese on ios, so this seems to be an issue that only occurs on android.

**Comment by tranquockhanh0506** [comment]
ohh, why i cannot, please give me your code ::))

**Comment by tranquockhanh0506** [comment]
can you detect japan string

**Comment by uchida-masanori** [comment]
@tranquockhanh0506 
> ohh, why i cannot, please give me your code ::))

I followed the notation on the [official page](https://pub.dev/packages/google_mlkit_text_recognition#:~:text=Requirements-,iOS,-%23).👍

and this is my case
ios：17.1.1
xcode：15.0.1

**Comment by njovy** [comment]
@tranquockhanh0506  I am getting the same exception for Korean recognizer.

**Comment by tranquockhanh0506** [comment]
@njovy  replace with this, work for me!

implementation 'com.google.mlkit:text-recognition-chinese:16.0.0'
implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0'
implementation 'com.google.mlkit:text-recognition-japanese:16.0.0'
implementation 'com.google.mlkit:text-recognition-korean:16.0.0
