### ISSUE TITLE
Capturig detected image

### ISSUE THREAD

**Issue by ammarbhatkar** [flutter-ml/google_ml_kit_flutter#550]
How to capture detected image i.e when user opens the camera as soon as face is detected the face image should be stored inside app loacl directory

**Comment by fbernaly** [comment]
Face detection plugin documentation is here: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_face_detection

Google's API documentation and capabilities is here: https://developers.google.com/ml-kit/vision/face-detection

Example app is here: https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/example

If you have an bug in the current API please use our template to report the bug.
