### ISSUE TITLE
Vertical Text Recognitio on iOS

### ISSUE THREAD

**Issue by manon-coulombe-octo** [flutter-ml/google_ml_kit_flutter#554]
Hello,

I would like to express my appreciation for the great work you've done with the library. It has been incredibly helpful.

I am writing to bring to your attention an issue I encountered while using the library on iOS. Currently, the text recognition feature seems to be limited to reading text only in the direction of the phone. Unlike the Android version, it doesn't recognize text on both horizontal and vertical axes.

I was wondering if there are plans to enhance the text recognition orientation on iOS, similar to the capabilities available on Android.

Thank you for your time and consideration. I look forward to hearing your thoughts on this matter.

Please find attached an illustration of the issue.

![Capture d’écran 2023-11-28 à 11 23 09](https://github.com/flutter-ml/google_ml_kit_flutter/assets/116719538/843ef9b4-aaf0-424f-9cfc-88d255af08f2)

**Comment by fbernaly** [comment]
@manon-coulombe-octo : 

This plugin is an un-official wrapper around [Google's API](https://developers.google.com/ml-kit), we are using [Flutter Method Channel](https://docs.flutter.dev/platform-integration/platform-channels) to pass the `InputImage` to the native layer in both iOS and Android. Ultimately, the processing is done by Google's API.
These are the recommend steps to debug your issue:
1. Try the API using Google's native apps from here:  https://github.com/googlesamples/mlkit 
2. If you can reproduce your issue using their apps then it is a bug that you need to report to them: https://github.com/googlesamples/mlkit
3. If their API is working okay and not able to reproduce your issue, then try our example app: https://github.com/flutter-ml/google_ml_kit_flutter/tree/develop/packages/example
4. If you are not able the reproduce the issue in our example app then compare the code we have in our example app and yours. I would put attention on how the orientation is handled in our app and compare it with yours. Most of the issues are related to wrong image orientation. ML Kit native API is very strict when it comes to `InputImage` orientation.
5. If you are able to reproduce in our example app them feel free to fork our repo and send a PR with your contribution. We are always happy to review contributions.

I hope this helps.

**Comment by EliseiNicolae** [comment]
Does anyone have a solution / workaround for this?

**Comment by EliseiNicolae** [comment]
Looks like the issue happens just on 'latin'

https://github.com/user-attachments/assets/13ec84d7-5e51-4e25-9bec-e4cbbecf7c2f
