### ISSUE TITLE
iOS pod installation

### ISSUE THREAD

**Issue by Gagandeep1408** [flutter-ml/google_ml_kit_flutter#557]
[!] Unable to find a specification for `google_mlkit_commons` depended upon by `google_mlkit_language_id`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by xiaolei1013** [comment]
same issue here. config from pubspec file: google_mlkit_language_id: ^0.9.0. any updates?

**Comment by xiaolei1013** [comment]
i've fixed this issue by explicitly adding google_mlkit_commons: ^0.6.1 in pubsepc
