### ISSUE TITLE
 After integrating google_ml_kit my project stops working.

### ISSUE THREAD

**Issue by AyeshaIftikhar** [flutter-ml/google_ml_kit_flutter#561]
**Title**:  After integrating google_ml_kit my project stops working.
**Describe the bug**
I am working on a project that required kYC verification for that I use `google_ml_kit` package for scanning Identity Card but it has made my application stopped working. And making my app's cloud_firestore to throw this exception `[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.`

**Platform (please complete the following information):**
 - OS: android
 - Device: Redmi 12C
 - OS: Android 12
 - Flutter/Dart Version: 3.16.0
- Plugin version: recent

**Comment by fbernaly** [comment]
@AyeshaIftikhar : First of all, `google_ml_kit` an umbrella plugin and you should be using instead the specific plugin for the functionality you want to use, I believe it is [google_mlkit_entity_extraction](https://pub.dev/packages/google_mlkit_entity_extraction) or [google_mlkit_text_recognition](https://pub.dev/packages/google_mlkit_text_recognition). 

Look at the closed issues this seems like a duplicated issue that someone already reported: https://github.com/flutter-ml/google_ml_kit_flutter/issues?q=is%3Aissue+cloud_firestore+is%3Aclosed

**Comment by AyeshaIftikhar** [comment]
@fbernaly 
I tried to use those but they also throws an exception or won't let the application to run

**Comment by bensonarafat** [comment]
This is a duplicate issue. 
See here [#286](https://github.com/flutter-ml/google_ml_kit_flutter/issues/286) 
contains possible fix
