### ISSUE TITLE
<google_mlkit_text_recognition errors during flutter build process>

### ISSUE THREAD

**Issue by niluved** [flutter-ml/google_ml_kit_flutter#563]
**Note: C:\Users\xxxxx\AppData\Local\Pub\Cache\hosted\pub.dev\google_mlkit_text_recognition-0.11.0\android\src\main\java\com\google_mlkit_text_recognition\TextRecognizer.java uses unchecked or unsafe operations.**: 

**Describe the bug**
I just added google_mlkit_text_recognition: ^0.11.0 in my pubspec.yaml and run my Flutter mobile app, but i get this warnings in my console:

Note: C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dev\google_mlkit_commons-0.6.1\android\src\main\java\com\google_mlkit_commons\InputImageConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\xxx\AppData\Local\Pub\Cache\hosted\pub.dev\google_mlkit_text_recognition-0.11.0\android\src\main\java\com\google_mlkit_text_recognition\TextRecognizer.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Platform**
 - Flutter/Dart Version: 3.13.7 / 3.1.3
- Plugin version: google_mlkit_text_recognition: ^0.11.0

**Comment by Artico77** [comment]
i'd like to know if this is expected or not

**Comment by PrimeTheFirst** [comment]
Same issue

**Comment by niluved** [comment]
the issue actually vanishes the second time the app builds

**Comment by AhmadAmmar260** [comment]
how you solve it

**Comment by niluved** [comment]
> how you solve it

as i said it disappears next time you build the app

**Comment by remsysinc** [comment]
It does only show the first build (or anytime after "flutter clean") but it's still red and scary at first.  Cannot seem to find a way to rid it, even with suppression code under "android/build.gradle.kts".
