### ISSUE TITLE
cannot support to convert to Thai language

### ISSUE THREAD

**Issue by bigboss27051** [flutter-ml/google_ml_kit_flutter#568]
flutter lib google_mlkit_text_recognition in version 0.11.0 cannot support Thai language 
<img width="891" alt="Screenshot 2567-01-09 at 16 11 30" src="https://github.com/flutter-ml/google_ml_kit_flutter/assets/14176569/ce9c61e2-d3b8-4fda-b16d-908cc18d4e9c">
<img width="884" alt="Screenshot 2567-01-09 at 16 11 39" src="https://github.com/flutter-ml/google_ml_kit_flutter/assets/14176569/35e18c69-7fbf-4851-8a83-0bc80c5f4b3f">
<img width="904" alt="Screenshot 2567-01-09 at 16 11 51" src="https://github.com/flutter-ml/google_ml_kit_flutter/assets/14176569/5c9dbae6-d6d8-4445-81dd-7c78f27b766e">

Ref: https://developers.google.com/ml-kit/vision/text-recognition/v2/languages

**Comment by fbernaly** [comment]
If your Language is not included in that list then it is not supported.

PLEASE reach out to Google directly with your request to add support for that language: 
- https://github.com/googlesamples/mlkit/issues
