### ISSUE TITLE
Support self-hosting ML models

### ISSUE THREAD

**Issue by AlienKevin** [flutter-ml/google_ml_kit_flutter#576]
**Title**
Support self-hosting ML models

**Describe the feature request**
ML models are currently downloaded from dl.google.com, which is blocked in countries like China. It would be very helpful if this library can support customization of the download URL domain to pull from a self-hosted server.

**Comment by fbernaly** [comment]
that is explained in the readme: 
https://github.com/flutter-ml/google_ml_kit_flutter/tree/master/packages/google_mlkit_object_detection#local-custom-model

**Comment by AlienKevin** [comment]
@fbernaly Thanks for the link. Does the DigitalInkRecognizer also support loading local custom model? I didn't see any instruction in the README so just want to confirm.

**Comment by fbernaly** [comment]
No, it does not

**Comment by AlienKevin** [comment]
Would it be possible to add support for the ink recognizer? If it's a similar process as the object detection than I can take a stab at it.
