### ISSUE TITLE
is this face detection ML Kit plugin able to detect only real  faces? 

### ISSUE THREAD

**Issue by AdeeshaP** [flutter-ml/google_ml_kit_flutter#579]
If I focus my Identity card also, it detects as a face. Is there any possibility to avoid that or this plugin detects any kind of faces whether they are real or not ?

**Comment by fbernaly** [comment]
This plugins detects all faces in a given image. Ultimately the photo of you id card is an image as well and it detects the faces in it. 
Maybe what you need is something like FaceId that uses the TrueDepth camera and machine learning for a secure authentication solution. Which is outside of the scope of this plugin.

Try something like this: 
https://github.com/SelectCode/FlutterTrueDepthCamera
