### ISSUE TITLE
New ML Kit Support to Flutter

### ISSUE THREAD

**Issue by myavuzokumus** [flutter-ml/google_ml_kit_flutter#581]
Google announced a new ML Kit, which is a Document scanner. Can you implement this in Flutter?

https://developers.google.com/ml-kit/vision/doc-scanner

**Comment by Sahil-kachhap** [comment]
I am interested in working on this Integration. If any one can please let me know how and from where can I start my contribution, it would be much helpful for me.

**Comment by bensonarafat** [comment]
@Sahil-kachhap 
I have plans on adding this new feature. No issue, we could work it together. 
That will cool
thanks

**Comment by Sahil-kachhap** [comment]
> @Sahil-kachhap I have plans on adding this new feature. No issue, we could work it together. That will cool thanks

Oh Ok, Let me know if I could of some help anywhere in here.

**Comment by fbernaly** [comment]
I do not have an ETA for this. Feel free to send a PR with your contributions.

**Comment by bensonarafat** [comment]
Can be assigned to me 
also @Sahil-kachhap 

@Sahil-kachhap  we can start from the docs from google [here](https://developers.google.com/ml-kit/vision/doc-scanner/android) and the package developed by @edwinmacalopu  [here](https://pub.dev/packages/cunning_document_scanner)

Document Scanner is still on beta for Android not currently on IOS 
for IOS, what @edwinmacalopu did was utilising the iOS native

**Comment by ablause** [comment]
Hi @bensonarafat, can you confirm whether you are currently working on this feature or whether you intend to start it? I'd like to understand the status and if you need any further help to make it happen. Thanks!

**Comment by bensonarafat** [comment]
@ablause yeah, i am currently working on the feature

**Comment by bensonarafat** [comment]
@edwinmacalopu @ablause 
can we connect on this?  
Trying to get activity on `onAttachedToActivity` 
can we talk about this. thanks

**Comment by ablause** [comment]
@bensonarafat, could you share the repository or link a PR to this issue so we can better understand or help you implement it. Thanks!

**Comment by bensonarafat** [comment]
Great @ablause 
Here is my fork repo https://github.com/bensonarafat/google_ml_kit_flutter 
We can continue from here. 
thanks

**Comment by fbernaly** [comment]
The feature in is development and testing. if you want to give it a try edit your yaml file and point it to

```
google_mlkit_document_scanner:
  git:
    url: https://github.com/flutter-ml/google_ml_kit_flutter.git
    ref: feature/doc_scanner
    path: packages/google_ml_kit_flutter
```

**Comment by bensonarafat** [comment]
This is also help. 

Wrote an article on it 

https://bensonarafat.medium.com/implementing-the-new-document-scanner-ml-kit-to-your-flutter-app-e3d978ef2957

**Comment by bensonarafat** [comment]
Closing this. 
Document scanner is now available

**Comment by ChenAce** [comment]
hey guys, may i know any plan to add iOS platform?

**Comment by ChenAce** [comment]
if the phone no google service, that means can not use the feature....

**Comment by ablause** [comment]
@ChenAce, it all depends on whether Google decides to integrate it into iOS as well.

I suggest exploring another package if you need iOS support. One option could be leveraging VisionKit by Apple for iOS and MLKit by Google for Android. Perhaps consider using this one: [flutter_doc_scanner](https://github.com/shirsh94/flutter_doc_scanner).

**Comment by ChenAce** [comment]
> @ChenAce, it all depends on whether Google decides to integrate it into iOS as well.
> 
> I suggest exploring another package if you need iOS support. One option could be leveraging VisionKit by Apple for iOS and MLKit by Google for Android. Perhaps consider using this one: [flutter_doc_scanner](https://github.com/shirsh94/flutter_doc_scanner).

hank you for your reply, but I have a suggestion. If we could extract the edge detection model for developers to use separately, wouldn't it be possible to take a single frame from the camera, pass it to the model, and after the model identifies the edges, return the position of the bounding box to be rendered on the preview frame? Wouldn't this make it dynamic?
