### ISSUE TITLE
ML_KIT face detection not working on IOS

### ISSUE THREAD

**Issue by mtalhastar** [flutter-ml/google_ml_kit_flutter#583]
Title: Face Detection not working on IOS 

My App captures screenshot ,converts that to input file, i pass that as input file to detectAndCropSingleFace() method
It is working well on Android but for IOS it detects no face from screenshot.

**To Reproduce**
1. Go to `
  Future<void> captureScreenshot() async {
    late Uint8List? imageBytes;
    
    
    await screenshotController.capture().then((Uint8List? image) {
      imageBytes = image;
      print(image.toString());
    }).catchError((onError) {
      print(onError);
    });
   #half of the image bytes are 0s on IOS , but not on android
    if (imageBytes != null) {
      final tempDir = await getTemporaryDirectory();
      final tempFilePath = '${tempDir.path}/temp_image.png';
      final file = await File(tempFilePath).writeAsBytes(imageBytes!);

      final facebytes = await detectAndCropSingleFace(file);
      if (facebytes == null) {
        HomeController.instance.imagesList.clear();
        HomeController.instance.celebrities.clear();
        Get.off(const HomePage(), transition: Transition.fade);
        return;
      }
      HomeController.instance.addImages(facebytes);

      if (counter < celebritiesLength - 1) {
        setState(() {
          counter++;
        });
      } else {
        Get.off(const ResultScreen());
      }
    }
  }`
2. Then `'  Future<Uint8List?> detectAndCropSingleFace(File imageFile) async {
   
    final faceDetector = FaceDetector(
        options: FaceDetectorOptions(
            enableTracking: true,
            enableLandmarks: true,
            enableClassification: true,
            enableContours: true));

    final inputImage = InputImage.fromFile(imageFile);
    try {
      final faces = await faceDetector.processImage(inputImage);
      if (faces.isEmpty) {
        Get.snackbar('Face Status ', 'No face in the image found');
        return null;
      }

      final face = faces.first;
      final rect = face.boundingBox;
      final x = rect.left.toInt();
      final y = rect.top.toInt();
      final width = rect.width.toInt();
      final height = rect.height.toInt();
      final originalImage = img.decodeImage(imageFile.readAsBytesSync())!;

      img.Image cropped = img.copyCrop(
        originalImage,
        x: x,
        y: y,
        width: width,
        height: height,
      );
      final croppedImageBytes = img.encodeJpg(cropped);
      final croppedFace = Uint8List.fromList(croppedImageBytes);
      await imageFile.delete();
      return croppedFace;
    } catch (e) {
      Get.snackbar('Error While detecting face ', 'Please try again');
      return null;
    } finally {
      await faceDetector.close();
    }
  }
'`
3. It works well on Android but no face gets detected on IOS
NOTE: half of the image bytes are 0s on IOS , but not on android after capturing screenshot

Expected
1.I expect it reads all the imagebytes with no 0s in it when running on IOS. 
2.getTemporaryDirectory() should also not make issues while accessing data
3.So image can get processed on IOS

**Platform (please complete the following information):**
 - OS: [e.g. iOS
 - Device: [Iphone 14 Simulator]
 - OS: [ iOS 17]
 - Flutter/Dart Version [3.13.7]
- google_mlkit_face_detection: ^0.8.0

**Comment by itzmail** [comment]
i still got error like this, Has anyone found a solution to this problem?

**Comment by mtalhastar** [comment]
Yes basically I was using WebView in flutter to capture face screenshots from the images, later came to know webview doesnt work with screenshots for IOS. Shifted to Inappwebview and my problem got solved.

**Comment by fbernaly** [comment]
Closing as @mtalhastar found a solution for his issue.
