### ISSUE TITLE
Add subject segmentation

### ISSUE THREAD

**Issue by jongkb** [flutter-ml/google_ml_kit_flutter#586]
It would be great if subject segmentation can be implemented.

[https://developers.google.com/ml-kit/vision/subject-segmentation](https://developers.google.com/ml-kit/vision/subject-segmentation)

**Comment by fuadreza** [comment]
Looking forward to this

**Comment by bensonarafat** [comment]
@fuadreza 
Yes, I'm working on it.

**Comment by bensonarafat** [comment]
Almost done this this issue...
Runing my test

**Comment by bensonarafat** [comment]
Almost done this this issue...
Runing my test

**Comment by bensonarafat** [comment]
Almost done with this issue...
Running my test
