### ISSUE TITLE
Why google ml kit doesn't support flutter web

### ISSUE THREAD

**Issue by simon-zhangmuye** [flutter-ml/google_ml_kit_flutter#597]
Hello, I am developing a Flutter Web application with the goal of integrating AI technology to provide real-time guidance for users on how to properly face the camera—for example, ensuring that their head position is neither too high nor too low. However, I've encountered a challenge: the machine learning libraries available for Flutter Web seem to be quite limited. I'm wondering whether it's possible to achieve this functionality? If so, how should I go about it?

**Comment by fbernaly** [comment]
Thanks for reaching out. This plugin is a Flutter wrapper for the native iOS and Android libraries that Google developed for their [ML Kit](https://developers.google.com/ml-kit) which is only available for mobile. In our README we explain that. If Google add that support for web we will wrap it here, but for now I think that is out of their scope.
