### ISSUE TITLE
Cant build an app on iOS simulator

### ISSUE THREAD

**Issue by vdnchnk** [flutter-ml/google_ml_kit_flutter#636]
Cant build an app on iOS simulator

After installing a plugin by guide faced with a problem, that app doesn't run on iOS simulator
The main error looks like this 
`Building for 'iOS-simulator', but linking in object file (/Users/.../ios/Pods/MLImage/Frameworks/MLImage.framework/MLImage[arm64][2](GMLImage.o)) built for 'iOS'`

Platform:
 - OS: IOS
 - Device: Simulator on MacBook Pro M1
 - OS: Sonoma 14.5
 - Flutter/Dart Version 3.22.0
- Plugin version google_mlkit_face_detection: ^0.11.0

**Comment by fbernaly** [comment]
These are the prerequisites for running on iOS

https://developers.google.com/ml-kit/migration/ios#prerequisites

I found this for running Google ML Kit on a simulator.

https://stackoverflow.com/questions/71656008/when-will-googlemlkit-support-arm64-simulator

For instance, if you want to test face detection with a camera, the simulator is not the answer, try testing on a real device.
