### ISSUE TITLE
MissingPluginException in Integration Tests

### ISSUE THREAD

**Issue by tylercodes1** [flutter-ml/google_ml_kit_flutter#640]
I am trying to write an integration test that ultimately makes a call to `TextRecognizer().processImage(inputImage)`, but it ultimately fails with
`MissingPluginException(No implementation found for method vision#startTextRecognizer on channel google_mlkit_text_recognizer)`

**To Reproduce**
[Code Sample](https://gist.github.com/tylercodes1/a28d7ce89848595445c19228ec244b2a)
1. Run the Integration test
2. See error

**Expected behavior**
I expected the integration test to run so that I am able to fully call my function `static Future<String> processImage(InputImage inputImage) async {}`.

**Screenshots**
_image_utils.dart_
![image](https://github.com/flutter-ml/google_ml_kit_flutter/assets/49599494/b149d457-2233-4b6e-80b7-8d2cc744b4dd)

**Platform (please complete the following information):**
 - OS: Web? (Integration Test)
 - Device: N/A
 - OS: N/A
 - Flutter/Dart Version [e.g. 22] 3.22.1 
- Plugin version ^0.11.0

**Comment by fbernaly** [comment]
This is in our README:

![Screenshot 2024-06-04 at 10 36 44 AM](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/c8806e1a-16fb-432c-808a-2321b7928216)

Also, in the pub.dev website:

![Screenshot 2024-06-04 at 10 38 01 AM](https://github.com/flutter-ml/google_ml_kit_flutter/assets/7014968/23923665-806c-4ad8-b628-e3e03c80ea47)
