### ISSUE TITLE
Android Firebase Conflict - FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by simeonangelov94** [flutter-ml/google_ml_kit_flutter#653]
There is a conflict between the firebase dependencies and the google_mlkit_object_detection: ^0.13.0 package. If I don't add the google_mlkit_object_detection package the app compiles without an issue 

  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_app_check: ^0.3.0+2
  google_mlkit_object_detection: ^0.13.0
  
  
  
  **FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':app:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.firebase.iid.FirebaseInstanceIdReceiver found in modules jetified-firebase-iid-20.1.5-runtime (com.google.firebase:firebase-iid:20.1.5) and jetified-firebase-messaging-24.0.0-runtime (com.google.firebase:firebase-messaging:24.0.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by simeonangelov94** [comment]
The conflict comes from having firebase_messaging: ^15.0.2 and google_mlkit_object_detection: ^0.13.0 packages in the yaml. When firebase_messaging: ^15.0.2 is removed there is no issue compiling for Android. Tried different build.gradle configuration but could fix it.

**Comment by fbernaly** [comment]
Other developers have reported similar issues when using some of the ML Plugins in combination with some of the Firebase plugins. Sometimes their native dependencies are not compatible. In that case you need to reach out to Google and post the issue in their repos because they need to fix that.

**Comment by simeonangelov94** [comment]
Do you have an idea where I can post this issue so the appropriate people can look into it?

**Comment by fbernaly** [comment]
https://github.com/googlesamples/mlkit/issues

**Comment by ahndwon** [comment]
Hello, have you found a solution?

**Comment by simeonangelov94** [comment]
No the only solution was to remove one of the dependencies. Tried customizing the gradle file but unsuccessfully.

**Comment by galizhan** [comment]
same issue
