### ISSUE TITLE
In google_mlkit_document_scanner, how could I scan document from Gallery instead of Camera ?

### ISSUE THREAD

**Issue by loveoverflowdev** [flutter-ml/google_ml_kit_flutter#654]

**Comment by bensonarafat** [comment]
Hi @loveoverflowdev 
Thanks for submitting an issue.
You can set the  ```isGalleryImport``` to ```true``` 
this will enable you use the gallery too

**Comment by fbernaly** [comment]
@loveoverflowdev : Please follow the issue template we created.

**Comment by loveoverflowdev** [comment]
> Hi @loveoverflowdev Thanks for submitting an issue. You can set the `isGalleryImport` to `true` this will enable you use the gallery too

Thank for your answer.

However, before that, I did set 
```
bool isGalleryImport = false
```
But I cannot see any gallery icon button to press
![image](https://github.com/user-attachments/assets/3d63d417-de32-4284-9002-7aa82096a3bc)
![image](https://github.com/user-attachments/assets/82b8e55f-8854-4c58-ac61-c39078d56a05)

**Comment by bensonarafat** [comment]
Could you reopen with the template as @fbernaly requested?

**Comment by loveoverflowdev** [comment]
> Could you reopen with the template as @fbernaly requested @loveoverflowdev ?

Of course, I have just created as your request:
[https://github.com/flutter-ml/google_ml_kit_flutter/issues/655](url)
