### ISSUE TITLE
Scan document from Gallery in google_mlkit_document_scanner

### ISSUE THREAD

**Issue by loveoverflowdev** [flutter-ml/google_ml_kit_flutter#655]
**Title**
In google_mlkit_document_scanner, I failed to enable document scanning from Gallery Instead of Camera

**Description**
In the google_mlkit_document_scanner package, I need to scan documents from the gallery instead of using the camera. I have set the boolean isGalleryImport to true in the source code, which is based on the ML Kit example. However, there is no gallery icon button visible to press for importing images from the gallery.

**To Reproduce**
1. Clone google_ml_kit_flutter from github repository
2. cd to google_ml_kit_flutter/packages/example
3. Edit packages/example/lib/vision_detector_views/document_scanner_view.dart: Change ```isGalleryImport``` to ```true```
![image](https://github.com/user-attachments/assets/5d453557-5f7a-4999-897a-48fa8f146945)
4. Run ```flutter build apk``` and then ```flutter install``` to launch ML Kit Flutter example on real Android device
5. See error: There is no gallery icon button to press for importing images from the gallery even after setting isGalleryImport to true.

**Screenshots**
![image](https://github.com/user-attachments/assets/b1c2a256-ae09-42a9-af81-8cd690e9c322)

**Expected behavior**
Appear Gallery icon button to pick image from Gallery

**Platform:**
- OS: Android
- Device: Samsung Galaxy A50
- OS: Android 11
- Flutter/Dart Version: Flutter 3.19.6 • channel stable
- Plugin version: google_mlkit_document_scanner 0.2.0

**Comment by bensonarafat** [comment]
![WhatsApp Image 2024-08-10 at 1 34 54 PM](https://github.com/user-attachments/assets/f4b520ed-bbbe-42a9-83c8-f99d2a98e3f3)

This is the result of a test I made. 
This seems to be working on my end.
Every possibility is can be from the device itself @loveoverflowdev
