### ISSUE TITLE
cloud_firestore/unavailable

### ISSUE THREAD

**Issue by 100Hamza** [flutter-ml/google_ml_kit_flutter#659]
cloud_firestore/unavailable

The actual statement of the error i'm getting "[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff." when i  remove the "google_ml_kit" package from the pubspec.yaml then i can login in to my system (android mobile) but when i add the "google_ml_kit", then just get the above mentioned statement, and i can't log in in to the system. 

**Platform**
 - OS: [Android]
 - Device: [vivo y15]
 - OS: [Android 11]
 - Flutter/Dart Version [3.22.2/3.4.3]
- Plugin version google_ml_kit: ^0.18.0

**Comment by bensonarafat** [comment]
@100Hamza 
Which of the packages are you using? 
Can you add the single package to your pubspec.yaml instead?
If you still get the error. Let me know
