### ISSUE TITLE
Report 'Update your Play Core Maven dependency' warning when packaging and listing using plugins

### ISSUE THREAD

**Issue by hhzhangzy** [flutter-ml/google_ml_kit_flutter#660]
Use google_mlkit_barcode_scanning(0.12.0) and google_mlkit_text_recognition(0.13.0)，When the engineering code was packaged in aab format and submitted for listing on the Google Play Market, a warning appeared as shown in the picture:
![企业微信截图_17222537804128](https://github.com/user-attachments/assets/581d1a1b-43f1-45be-b21f-850e64fe7ada)

+--- com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2
|    +--- com.google.android.datatransport:transport-api:2.2.1 -> 3.0.0 (*)
|    +--- com.google.android.datatransport:transport-backend-cct:2.3.3 -> 3.1.9 (*)
|    +--- com.google.android.datatransport:transport-runtime:2.2.6 -> 3.1.9 (*)
|    +--- com.google.android.gms:play-services-base:18.0.1 -> 18.1.0 (*)
|    +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.2.0 (*)
|    +--- com.google.android.play:core:1.10.0
|    +--- com.google.firebase:firebase-components:16.1.0 -> 17.1.5 (*)
|    \--- com.google.mlkit:common:18.0.0 -> 18.9.0 (*)

How to update the SDK to resolve this warning?

**Comment by hhzhangzy** [comment]
Is it caused by an additional dependency on 'implementation 'com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2' ?

**Comment by priyaa29** [comment]
Any update in this facing same issue ---  Update your com.google.android.play:core:1.10.0 Maven dependency to an Android 14 compatible version! Your current com.google.android.play:core:1.10.0 library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, 2024, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes. Please can anyone help with it if it is resolved.

**Comment by fbernaly** [comment]
I do not have an ETA, but you are welcome to send a PR with your contribution. Contributions are always welcome and more likely to be reviewed, merged and release in a new version.

**Comment by bensonarafat** [comment]
@hhzhangzy @priyaa29 
None of these dependencies are used in this package 

> 
> +--- com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2
> | +--- com.google.android.datatransport:transport-api:2.2.1 -> 3.0.0 ()
> | +--- com.google.android.datatransport:transport-backend-cct:2.3.3 -> 3.1.9 ()
> | +--- com.google.android.datatransport:transport-runtime:2.2.6 -> 3.1.9 ()
> | +--- com.google.android.gms:play-services-base:18.0.1 -> 18.1.0 ()
> | +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.2.0 ()
> | +--- com.google.android.play:core:1.10.0
> | +--- com.google.firebase:firebase-components:16.1.0 -> 17.1.5 ()
> | --- com.google.mlkit:common:18.0.0 -> 18.9.0 (*)

**Comment by priyaa29** [comment]
> @hhzhangzy @priyaa29 None of these dependencies are used in this package, are you sure it from this package
> 
> > +--- com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2
> > | +--- com.google.android.datatransport:transport-api:2.2.1 -> 3.0.0 ()
> > | +--- com.google.android.datatransport:transport-backend-cct:2.3.3 -> 3.1.9 ()
> > | +--- com.google.android.datatransport:transport-runtime:2.2.6 -> 3.1.9 ()
> > | +--- com.google.android.gms:play-services-base:18.0.1 -> 18.1.0 ()
> > | +--- com.google.android.gms:play-services-basement:18.0.0 -> 18.2.0 ()
> > | +--- com.google.android.play:core:1.10.0
> > | +--- com.google.firebase:firebase-components:16.1.0 -> 17.1.5 ()
> > | --- com.google.mlkit:common:18.0.0 -> 18.9.0 (*)

In this package, it is currently set to minSdkVersion: 21, targetSdkVersion: 33, and compileSdkVersion: 34. I'm trying to change it to targetSdkVersion: 34 and compileSdkVersion: 34. I'm using OCR detection with TextDetector, and I tried removing the implementation 'com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2' from the build.gradle file, but nothing is working. The Play Console is not allowing me to upload the bundle. If the error is not related to this package, is there a way to check which package is affected? Please let me know.

**Comment by bensonarafat** [comment]
@priyaa29 @hhzhangzy 

Read [here](https://developer.android.com/guide/playcore#playcore-migration) 
Also [here](https://stackoverflow.com/questions/78646430/play-console-warning-update-your-play-core-maven-dependency-to-an-android-14-co) 

The issue is not related to this package but I hope this will help you

**Comment by bensonarafat** [comment]
@priyaa29 
This seems to be a transitive dependency and coming from `com.google.mlkit:playstore-dynamic-feature-support:16.0.0-beta2`

This was not added to the library so this warning is completely up to Google

**Comment by bensonarafat** [comment]
#671 should fix this issue. 
Pls, if you still get this, feel free to reopen it
