### ISSUE TITLE
<google_mlkit_face_detection package not detecting face from camera image.>

### ISSUE THREAD

**Issue by Jayakumar-AndroidDev** [flutter-ml/google_ml_kit_flutter#662]
I checked every aspect i don't get a idea why it's not working i checked format, bytes but i can detect face when i get image from file,
**I want to detect face using google_mlkit_face_detection package and camera package real time**

`void faceDetect(CameraImage image) {
    try {

      final WriteBuffer allBytes = WriteBuffer();

      for (Plane plane in image.planes) {
        allBytes.putUint8List(plane.bytes);
      }

      final bytes = allBytes.done().buffer.asUint8List();

      final size = Size(
        image.width.toDouble(),
        image.height.toDouble(),
      );

      const rotation = InputImageRotation.rotation270deg;

      final metaData = InputImageMetadata(
        size: size,
        rotation: rotation,
        format: InputImageFormat.yuv420,
        bytesPerRow: image.planes[0].bytesPerRow,
      );

      final inputImage = InputImage.fromBytes(
        bytes: bytes,
        metadata: metaData,
      );

      faceDetector.processImage(inputImage).then(
        (detectedFace) {
          debugPrint('detected_face:- ${detectedFace.length}');
        },
      ).catchError((e) {
        debugPrint('ERROR_MESSAGE:- $e');
      });
    } catch (e) {
      debugPrint('ERROR_MESSAGE:- $e');
    }
  }
`

**Comment by bensonarafat** [comment]
@Jayakumar-AndroidDev 
Please, follow the issue template. 
I will be able to reproduce this from my end.
