### ISSUE TITLE
targetSdkVersion: 33 in Android 

### ISSUE THREAD

**Issue by priyaa29** [flutter-ml/google_ml_kit_flutter#664]
Update your com.google.android.play:core:1.10.0 Maven dependency to an Android 14 compatible version! Your current com.google.android.play:core:1.10.0 library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers. As a reminder, from August 31, 2024, Google Play requires all new app releases to target Android 14. Update to the latest library version dependency to avoid app crashes.-  Getting this while updating the App my app in google play console.

**Comment by fbernaly** [comment]
You are welcome to send a PR with your contribution. Contributions are always welcome and more likely to be reviewed, merged and release in a new version.

**Comment by bensonarafat** [comment]
@priyaa29 
I am closing this, this plugin does not depend on com.google.android.play:core. 
It must be from another plugin you are using in your app.

**Comment by bensonarafat** [comment]
duplicate. 
Closing

**Comment by fbernaly** [comment]
@bensonarafat: could you add to which issue this one duplicates?

**Comment by bensonarafat** [comment]
> @bensonarafat: could you add to which issue this one duplicates?

[Here](https://github.com/flutter-ml/google_ml_kit_flutter/issues/660#issue-2436768843)  @fbernaly
