### ISSUE TITLE
Migrate Example to Flutter 3.24

### ISSUE THREAD

**Issue by rs5173** [flutter-ml/google_ml_kit_flutter#665]
Flutter 3.24 will report an error when running the example, and some bearkchanges need to be fixed

**Comment by bensonarafat** [comment]
@rs5173 
What errors are you having? 
What device? 
We have an issue template to use. 
I will close this, If you don't provide that I can help you

**Comment by fbernaly** [comment]
@rs5173 : Follow template to report issue.
