### ISSUE TITLE
Document scanner platform exception on camera preview cancel

### ISSUE THREAD

**Issue by LavanDroid** [flutter-ml/google_ml_kit_flutter#667]
Facing platform exception on camera preview cancel while running in android device. Below I have attached the error log.

Using library: google_mlkit_document_scanner: ^0.2.0

**Error log:**
E/flutter (16670): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DocumentScanner, Operation cancelled, null, null)
E/flutter (16670): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (16670): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (16670): <asynchronous suspension>
E/flutter (16670): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
E/flutter (16670): <asynchronous suspension>
E/flutter (16670): #3      DocumentScanner.scanDocument (package:google_mlkit_document_scanner/src/document_scanner.dart:19:29)
E/flutter (16670): <asynchronous suspension>

E/GmsDocScanDelAct(16670): Failed to handle scanning result
E/GmsDocScanDelAct(16670): java.lang.IllegalStateException: Failed to handle result
E/GmsDocScanDelAct(16670): 	at com.google.mlkit.vision.documentscanner.internal.zzg.run(com.google.android.gms:play-services-mlkit-document-scanner@@16.0.0-beta1:12)
E/GmsDocScanDelAct(16670): 	at android.os.Handler.handleCallback(Handler.java:938)
E/GmsDocScanDelAct(16670): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/GmsDocScanDelAct(16670): 	at android.os.Looper.loopOnce(Looper.java:226)
E/GmsDocScanDelAct(16670): 	at android.os.Looper.loop(Looper.java:313)
E/GmsDocScanDelAct(16670): 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by bensonarafat** [comment]
@LavanDroid 
Please follow the issue template so I can help with the issue. 
Right now, I don't know what version of Flutter SDK you are using or what Android version 
I must close it, so you open another with the right template. 
thanks
