### ISSUE TITLE
Firestore database and google ml face detection problem

### ISSUE THREAD

**Issue by ajmi-dhia** [flutter-ml/google_ml_kit_flutter#672]
I'm working on an app using firebase and google ml face detection
Since I added google_ml_face_detection I started facing a problem with firestore database and firebase authentification works fine
This problem is on Android only on ios it works correctly
Ps: I added the implementation in app/build.gradle 
Can anyone help please?

**Comment by bensonarafat** [comment]
@ajmi-dhia 
What is the log? 
Could you reopen the issue with the issue template
