### ISSUE TITLE
Issue when scanning image taken in landscape.

### ISSUE THREAD

**Issue by shijinthottiyil** [flutter-ml/google_ml_kit_flutter#673]
when we take an image using camera in portrait mode text recognition works fine but in landscape mode last line is appearing first

**Comment by lthoedt** [comment]
For me landscape only works on android, ios only works in Portrait. Seems like they do not have orientation implemented right.

**Comment by fbernaly** [comment]
Both iOS and Android work in the example app. Have you give a try? Try to follow the implementation we have in the example app. If you encounter the same issue in the example app we are always open to PRs and contributions. Thanks.

**Comment by shijinthottiyil** [comment]
Yes

**Comment by shijinthottiyil** [comment]
But it's not working on everytime. Some time it works other wise.On landscape mode it scans from the bottom
