### ISSUE TITLE
Compatibility Issue: GoogleTransport 10.x

### ISSUE THREAD

**Issue by rennylangat** [flutter-ml/google_ml_kit_flutter#681]
Currently to get the package working on iOS, one has to downgrade other Google dependencies mostly Firebase ones (e.g Firebase Analytics 10.x). When can we get this dependency updated since GoogleTransport is already upgraded for all others?

### Steps to reproduce.

1. Upgrade `google_ml_kit_flutter` to 0.11.1 (or latest version)
2. Upgrade `firebase_core` to 3.5.0
 - You can upgrade other firebase dependencies as well
3. Run the project and target iOS device  

### What is the expected result?

An error occurs during cocoa pods installation/updating. 
The specific error thrown is pasted below
`CocoaPods could not find compatible versions for pod "GoogleDataTransport"`

### Did you try our example app?

Yes

### Is it reproducible in the example app?

No

### Reproducible in which OS?

iOS

### Flutter/Dart Version?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.1 24B5046f darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.91.1)
[✓] VS Code (version 1.94.0-insider)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for *** Apple Watch. Ensure the device is unlocked and discoverable via
      Bluetooth. (code -27)
    ! Error: Browsing on the local area network for ***. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for *** iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!`

### Plugin Version?

0.11.1

**Comment by fbernaly** [comment]
Duplicates: https://github.com/flutter-ml/google_ml_kit_flutter/issues/669

**Comment by fbernaly** [comment]
Refer to https://github.com/flutter-ml/google_ml_kit_flutter/issues/669#issuecomment-2363883077
