### ISSUE TITLE
Use platform_interface

### ISSUE THREAD

**Issue by alihassan143** [flutter-ml/google_ml_kit_flutter#687]
### Describe your issue. If applicable, add screenshots to help explain your problem.

Currently, the latest version of Firebase is causing compatibility issues with Google ML Kit because both use different versions of the Google Data Transport library. To resolve this:

	•	Use the [Path Provider](https://github.com/flutter/packages/tree/main/packages/path_provider) package like path_provider_platform_interface.
	•	For Android, you can use the google_mlkit_android package.
	•	For iOS, use the google_mlkit_ios package.

This approach avoids version conflicts and simplifies future development, as you don’t need to do anything else for platform-specific dependencies.

### Steps to reproduce.

 flutter 

### What is the expected result?

new version

### Did you try our example app?

Yes

### Is it reproducible in the example app?

Yes

### Reproducible in which OS?

iOS and Android

### Flutter/Dart Version?

latest

### Plugin Version?

latest

**Comment by bensonarafat** [comment]
Is this just iOS or both iOS and Android ?? @alihassan143

**Comment by alihassan143** [comment]
kindly don't close it feature related request

**Comment by alihassan143** [comment]
we need to change the structure of the plugin system just to make them more compatible that if developer don't want to use one platform side things he can do that

**Comment by alihassan143** [comment]
<img width="695" alt="Screenshot 2024-10-01 at 8 29 23 PM" src="https://github.com/user-attachments/assets/7a3a8390-0e38-42e9-962b-39903b24b07f">
<img width="777" alt="Screenshot 2024-10-01 at 8 29 45 PM" src="https://github.com/user-attachments/assets/60a4cc67-4067-4e68-a4a4-4bfa109936bb">

**Comment by alihassan143** [comment]
just like that 
<img width="910" alt="Screenshot 2024-10-01 at 8 30 20 PM" src="https://github.com/user-attachments/assets/d8d050bf-767f-4a89-8265-1e40f99bc9bd">
we can connect them using this
