### ISSUE TITLE
Dependency conflict with firebase_core - CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":

### ISSUE THREAD

**Issue by Trejay** [flutter-ml/google_ml_kit_flutter#690]
### Describe your issue. If applicable, add screenshots to help explain your problem.

When using firebase_core: 3.6.0 there is a dependency conflict with google_mlkit_barcode_scanning: 0.12.1

Here is the IOS build output:

Analyzing dependencies
firebase_auth: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
      Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseCore (= 11.2.0) was resolved to 11.2.0, which depends on
          GoogleUtilities/Environment (~> 8.0)

    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.6.0, which depends on
      Firebase/CoreOnly (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseCore (= 11.2.0) was resolved to 11.2.0, which depends on
          GoogleUtilities/Logger (~> 8.0) was resolved to 8.0.2, which depends on
            GoogleUtilities/Environment (= 8.0.2)

    google_mlkit_barcode_scanning (from `.symlinks/plugins/google_mlkit_barcode_scanning/ios`) was resolved to 0.12.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              GoogleUtilities/Environment (~> 7.7)
              
It looks like MLKitCommon 11.0 (https://developers.google.com/ml-kit/release-notes) is the latest that depends on  GoogleDataTransport <10.0, >= 9.4.1
which in turn has the following dependency 
GoogleUtilities/Environment (~> 7.7)
Which makes it incompatible with firebase_core which relies on GoogleUtilities/Environment (~> 8.0)

It looks like GoogleDataTransport has been removed as a GoogleUtilities dependency in version 10.0:
(see https://github.com/google/GoogleDataTransport/releases/tag/10.0.0)

I guess when MLKitCommon upgrades it dependency on GoogleDataTransport  to >=10.0
it should fix the issue.

### Steps to reproduce.

In the flutter pubspec.yml, include the following packages:
firebase_core: 3.5.0
google_mlkit_barcode_scanning: ^0.12.1

Then try an IOS build (Android does not have this issue)

### What is the expected result?

MLKitCommon needs to upgrade it dependency on GoogleDataTransport  to >=10.0

### Did you try our example app?

No

### Is it reproducible in the example app?

No

### Reproducible in which OS?

iOS

### Flutter/Dart Version?

flutter --version: Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 months ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (3 months ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.85.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.

### Plugin Version?

google_mlkit_barcode_scanning: 0.12.1

**Comment by bensonarafat** [comment]
@Trejay 
Thanks for submitting the issue, this is related to this [here](https://github.com/flutter-ml/google_ml_kit_flutter/issues/669)
I have to close this issue. 
When there is an update from Google about the dependencies, I will update it correctly.
