### ISSUE TITLE
Enhancement request: Add info on how to build standalone example app

### ISSUE THREAD

**Issue by rettops** [flutter-ml/google_ml_kit_flutter#694]
### Describe your issue. If applicable, add screenshots to help explain your problem.

As a Flutter novice, I tried to pull out and build just the example app. It would really help if the example app README had instructions on how to modify the example app to use the published google_ml_kit instead of relying on the full kit sources. I found that I needed to modify the example/analysis_options.yaml and the example/pubspec.yaml.

### Steps to reproduce.

1. clone the github repo
2. copy packages/example to another location
3. try to build it

### What is the expected result?

A working example / instructions on how to build a working example standalone.

### Did you try our example app?

Yes

### Is it reproducible in the example app?

Yes

### Reproducible in which OS?

Android

### Flutter/Dart Version?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.0)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

### Plugin Version?

0.18.1

**Comment by fbernaly** [comment]
@rettops : based on your experience feel free to send a PR with the points that should be improved in the example app README and docs.

**Comment by rettops** [comment]
@fbernaly OK.

It looks like it would be easiest to add a pubspec.yaml.standalone to packages/example, and modify the example/README.md to explain how to swap it in if you want to build the example standalone. Would that be OK with you?

Also, I'd like to make sure that everything works as it should with the standalone pubspec.yaml. Are there integration tests, or is testing done by hand?

**Comment by fbernaly** [comment]
Send me the PR and I will take a look.
Unfortunately testing is done by hand.
