### ISSUE TITLE
The performance of Face Detection is terrible

### ISSUE THREAD

**Issue by Henriquek47** [flutter-ml/google_ml_kit_flutter#698]
### Describe your issue. If applicable, add screenshots to help explain your problem.

Why does face detection lag, making it seem like there's a delay?

### Steps to reproduce.

.

### What is the expected result?

.

### Did you try our example app?

Yes

### Is it reproducible in the example app?

Yes

### Reproducible in which OS?

Android

### Plugin Version?

.

**Comment by fbernaly** [comment]
Feel free to send a PR with your contributions. This is an non-Google-sponsored, open-source, plugin. We always welcome contributions.
