### ISSUE TITLE
On emulator, Document Scanner throws "PlatformException(DocumentScanner, Failed to start document scanner, null, null)"

### ISSUE THREAD

**Issue by pamtbaau** [flutter-ml/google_ml_kit_flutter#699]
### Describe your issue. If applicable, add screenshots to help explain your problem.

When running my Flutter app on physical device all goes well. When using Android emulator an error is thrown when running code line:
```
final documents = await documentScanner.scanDocument();
```
Complete dump of log when above statement is being called:
```
D/EGL_emulation( 2505): app_time_stats: avg=4815.07ms min=4.14ms max=43090.05ms count=9
D/TransportRuntime.SQLiteEventStore( 2505): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
I/flutter ( 2505): PlatformException(DocumentScanner, Failed to start document scanner, null, null)
D/TransportRuntime.JobInfoScheduler( 2505): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore( 2505): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 2505): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
```

### Steps to reproduce.

1. Create new flutter app using `flutter create test --platform=android`
2. In pubspec.yaml, add:
    ```
    dependencies:
      ...
      google_mlkit_document_scanner: ^0.3.0
    ```
4. Replace content of `main.dart` with:
    ```
    import 'package:flutter/material.dart';
    import 'package:google_mlkit_document_scanner/google_mlkit_document_scanner.dart';

    void main() {
      runApp(const MyApp());
    }

    class MyApp extends StatelessWidget {
      const MyApp({super.key});

      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          home: Scaffold(
            body: Center(
              child: IconButton(
                onPressed: _onCameraPressed,
                icon: const Icon(Icons.camera_alt),
              ),
            ),
          ),
        );
      }

      Future<void> _onCameraPressed() async {
        final options = DocumentScannerOptions();

        try {
          final documentScanner = DocumentScanner(options: options);
          final documents = await documentScanner.scanDocument();
        } catch (ex) {
          print(ex);
        }
      }
    }
    ```
5. Run app on emulator using Android 14
6. See printed error
    ```
    PlatformException(DocumentScanner, Failed to start document scanner, null, null)
    ```
7. Run app on mobile device using Android 14 and all goes well.

### What is the expected result?

As on my mobile phone camera should  appear and document scanning should be started.

### Did you try our example app?

No

### Is it reproducible in the example app?

No

### Reproducible in which OS?

Android

### Flutter/Dart Version?

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4249], locale nl-NL)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.6.4)
[!] Android Studio (version 2022.2)
    ✗ Unable to determine bundled Java version.
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.1)
[✓] Connected device (3 available)
    ! Device emulator-5554 is offline.
[✓] Network resources

! Doctor found issues in 1 category.

### Plugin Version?

VSCode Flutter plugin: v3.98.0
VSCode Dart plugin: v3.98.1
pubspec.yaml dependency: google_mlkit_document_scanner: ^0.3.0

**Comment by bensonarafat** [comment]
@pamtbaau You can't use an emulator for a document scanner

**Comment by pamtbaau** [comment]
Any reason why?

**Comment by bensonarafat** [comment]
Document Scanner requires the Play Store service

**Comment by pamtbaau** [comment]
Ok thanks. That's a bummer... It might be worthwhile to add that to the documentation. Or have I missed something?
