### ISSUE TITLE
barcode scanning support for GS1

### ISSUE THREAD

**Issue by maciogg** [flutter-ml/google_ml_kit_flutter#701]
### Describe your issue. If applicable, add screenshots to help explain your problem.

Does the plugin allow for GS1 code recognition (specifically GS1 Databar Expanded Stacked)? I can't find it. If not, is it planned?

### Steps to reproduce.

Processing image with GS1 Databar Expanded Stacked

### What is the expected result?

GS1 Databar Expanded Stacked recognition

### Did you try our example app?

Yes

### Is it reproducible in the example app?

No

### Reproducible in which OS?

iOS and Android

### Flutter/Dart Version?

3.24.3

### Plugin Version?

  google_mlkit_barcode_scanning: ^0.13.0

**Comment by fbernaly** [comment]
These are the formats:

https://developers.google.com/ml-kit/vision/barcode-scanning#key_capabilities

https://github.com/flutter-ml/google_ml_kit_flutter/blob/master/packages/google_mlkit_barcode_scanning/lib/src/barcode_scanner.dart#L44-L88

Other than that is outside the scope of this plugin-wrapper. 

If the format you require is not listed there then request the feature to Google directly.
